### PR TITLE
Ignore ApplicationInsights.config for Microsoft Azure

### PR DESCRIPTION
**Pull request by anderslundsgard**
The feature Application Insights in Microsoft Azure is cool but the config file ApplicationInsights.config should not be in version control.

According to https://azure.microsoft.com/sv-se/blog/upcoming-name-change-for-windows-azure/ Windows Azure is also renamed to Microsoft Azure.

### CODE REVIEW

**Comment by shiftkey** [comment]
@anderslundsgard do you have any links to documentation around this, so that others can understand this requirement?

**Comment by anderslundsgard** [comment]
Yes, here is a good introduction to ApplicationInsights http://docs.asp.net/en/latest/fundamentals/application-insights.html
The docs don't explicit tells that you should not share the config file but I guess others like me don't like to share the <InstrumentationKey> that is found in ApplicationInsights.config.

**Comment by shiftkey** [comment]
@anderslundsgard and for reference, can you share what sort of stuff is in your created `ApplicationInsights.config` file (with the contents sanitized wherever neessary)? I'm not really familiar with AppInsights, so it's mostly for my benefit :grin:

It might also be worth submitting a PR to those docs to explain the `.config` file further - and that it can be safely ignored - but I won't hold this up further.

cc @ardalis for a :thumbsup: on this PR

**Comment by anderslundsgard** [comment]
The element I got stuck on was the InstrumentationKey GUID that is your unique key to send statistics of site usage to Azure.
```
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
    ...
    <InstrumentationKey>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</InstrumentationKey>
</ApplicationInsights>
```

**Comment by shiftkey** [comment]
@anderslundsgard thanks, I'll get this in and if others decided they have differing opinions we can revisit

**Comment by anderslundsgard** [comment]
Great, thanks!

**Comment by gitFurious** [comment]
This change breaks [continuous deployment from github through the Azure portal](https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/#Step75).

InstrumentationKey isn't a secret. In fact, [it's used on client side web pages](https://www.visualstudio.com/en-us/get-started/insights/app-insights-asp-net).

**Comment by anderslundsgard** [comment]
Ok, I have not experienced that (yet) but then i totally agree with you @gitFurious.

**Comment by shiftkey** [comment]
@gitFurious thanks for bringing this to our attention. I'd gladly take a patch to revert this before the damage goes any further...

**Pull request merged**
