### PR TITLE
Removed project files from gitignore for UE

### PR DESCRIPTION
**Pull request by apap04**
**Reasons for making this change:**

So project files won't be ignored in games with code. These files shouldn't be ignored, even if the game has no code.

### CODE REVIEW

**Comment by shiftkey** [comment]
cc @samsheff @robipresotto for feedback as they added these rules

**Comment by shiftkey** [comment]
@apap04 any links to StackOverflow discussions or other documentation about how this change is beneficial?

**Comment by robipresotto** [comment]
The files should be ignored because it's auto-generated by the engine and could contain personal configuration. I don't see any benefit in that changes.

**Comment by shiftkey** [comment]
> The files should be ignored because it's auto-generated by the engine and could contain personal configuration.

@apap04 thoughts on ☝️ ?

**Pull request closed without merging**
