### PR TITLE
Update JetBrains.gitignore according to the official knowledge base article

### PR DESCRIPTION
**Pull request by LazarusX**
The current JetBrains.gitignore file contains several entries which are suggested to be shared, such as the project .ipr file and the .iml module files, according to [the official knowledge base article](https://intellij-support.jetbrains.com/entries/23393067). This commit fix this issue.

### CODE REVIEW

**Comment by shiftkey** [comment]
This seems to be a more complete version of #1399

**Comment by shiftkey** [comment]
@LazarusX unfortunately this isn't mergeable currently, and the link now requires an account signup to access it :cry: But it looks promising, judging by the documentation. Are you able to update this?

I need to clean up stale pull requests at some stage, and will close this out if I don't hear anything before **Friday 26th February**.

**Comment by LazarusX** [comment]
Hi @shiftkey,

I just resolved the conflicts and this is now mergeable. The documentation is now redirected [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) and does not require login to access. You can check it out to verify the changes.

Entries such as `.idea/sqlDataSources.xml` and `.idea/dynamic.xml`, are not mentioned in the documentation. I tend to leave them in the `.gitignore` because they look sensitive and I am not 100% sure that they can be shared.

**Comment by shiftkey** [comment]
> The documentation is now redirected [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) and does not require login to access.

Great, thanks!

> ... I tend to leave them in the .gitignore because they look sensitive and I am not 100% sure that they can be shared.

This is fine - with the change to track `.idea` by default it's good to exclude those known files again.

**Pull request merged**
