### PR TITLE
[ADD] Added *.pyc and *.DS_Store

### PR DESCRIPTION
**Pull request by altela**
**Reasons for making this change:**
I would like to simply add *.pyc and *.DS_Store into the python .gitignore

### CODE REVIEW

**Comment by movatica** [comment]
.DS_Store files are not Python-related.

**Comment by altela** [comment]
Ok i will update it and remove

**Review by khr1stopher — APPROVED** [review]

**Comment by zonuexe** [comment]
Why add `*.pyc`? It looks like this pattern already has you covered.

https://github.com/github/gitignore/blob/a60d59238afb22523038b549b9b27f15734f7563/Python.gitignore#L3

**Comment by altela** [comment]
yes but it doesn't seem to work, perhaps this happen on my local so i guess i will close it

**Pull request closed without merging**
