### PR TITLE
Added JMeter gitignore

### PR DESCRIPTION
**Pull request by RohanSakhale**
**Reasons for making this change:**

This Pull Request contains new gitignore template for JMeter Performance Testing Tool

If this is a new template: 

 - **Link to application or project’s homepage**:  [http://jmeter.apache.org](http://jmeter.apache.org)

### CODE REVIEW

**Comment by joeblau** [comment]
@RohanSakhale - This tempalte is live on [gitignore.io](https://www.gitignore.io) - https://www.gitignore.io/api/jmeter

**Comment by RohanSakhale** [comment]
Thanks @joeblau can this PR be accepted in this repository

**Comment by joeblau** [comment]
I'm not a maintainer on this repository or @github, I maintain @dvcs.  I merged this change into gitignore.io last May.

**Comment by RohanSakhale** [comment]
No issues @joeblau, Thanks 👍

**Comment by shiftkey** [comment]
@RohanSakhale apologies for the delay in responding.

I'm going to close this out because the value of maintaining a template like this in the repository isn't clear to me.

If you still feel this should be a template listed in this repository, please read the section about [specialized templates](https://github.com/github/gitignore#specialized-templates) and open a new pull request that follows the new pattern.

**Pull request closed without merging**
