### PR TITLE
Update Android.gitignore

### PR DESCRIPTION
**Pull request by ChArslan**

### CODE REVIEW

**Comment by shiftkey** [comment]
Can you tell me a bit about why this rule should be added, and if there's any supporting links or documentation that we can point curious users to?

**Comment by ChArslan** [comment]
All resources file used in Android with .xml extension like make a layout for your App 
[](http://www.tutorialspoint.com/android/android_resources.htm) @shiftkey

**Comment by ChArslan** [comment]
[](http://www.tutorialspoint.com/android/android_resources.htm)

**Comment by shiftkey** [comment]
@ChArslan I'm still not clear on the files related to this change - are there files named `.xml` (no wildcard, no specific name) which should be ignored in an Android project?

**Comment by rafaelloab** [comment]
It doesn't make sense, there are files like AndroidManifest.xml and many other xml files related to the View component of the app and they are essential. Hardly someone would not versionate those files.

**Comment by shiftkey** [comment]
@ChArslan I'm still concerned with the same things that @rafaelloab has raised - XML files should be version controlled in most scenarios. If there are scenarios were an XML file can be safely ignored, it should be a specific rule with a comment to explain why this can be done.

**Comment by shiftkey** [comment]
Closing due to conflicts and inactivity. @ChArslan please have a look at the latest file and see if anything needs to be incorporated.

**Pull request closed without merging**
