### PR TITLE
* DS_Store ignored for Unity.gitignore

### PR DESCRIPTION
**Pull request by mopsicus**

### CODE REVIEW

**Comment by r-ush** [comment]
DS_Store is not something not related to unity but mac os specifically, so in my opinion, it isn't required here.

**Comment by mopsicus** [comment]
Anyway all mac users add it to gitignore by themselves

**Comment by bl-ue** [comment]
Mac users (like myself) can use https://github.com/github/gitignore/blob/master/Global/macOS.gitignore in conjuection with Unity.gitignore.

**Comment by mopsicus** [comment]
Roger that

**Pull request closed without merging**
