### PR TITLE
Added IDE Files to Java template

### PR DESCRIPTION
**Pull request by rahilsh**
**Reasons for making this change:**

Wanted to add missing IDE files, I am sure it will be helpful for all IDE users

**Links to documentation supporting these rule changes:**

NA

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by rahilsh** [comment]
@53jk1 Thanks but I don't see an option to merge, do you? I think only admin of this repo can merge. Are you an admin?

**Comment by rahilsh** [comment]
@shiftkey Can you help merge this

**Comment by bl-ue** [comment]
ping @bdougie @martinwoodward

@rahilsh they're maintaining it now 🤷🏻‍♂️

**Comment by martinwoodward** [comment]
Had a chat with the JetBrains folks over the weekend and they don't recommend ignoring the entire .idea folder so don't want to pull it into here. Best instead to merge the JetBrains.ignore with this Java one for your repo if you wanted and/or set your global .gitignore to exclude the relevant files or the entire folder of you wish.

**Pull request closed without merging**
