### PR TITLE
Update Gradle.gitignore

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by shiftkey** [comment]
@sleben I'm curious - is this a recent change or just a feature most us don't know about?

**Comment by sieben** [comment]
I really don't know. This file just popped up inside my folder. I'm using
Gradle 2.6.

2015-08-24 13:09 GMT+02:00 Brendan Forster <notifications@github.com>:

**Comment by sieben** [comment]
@shiftkey do you think it's merging material?

**Comment by shiftkey** [comment]
@sieben the path is specific enough, and that "prior art" definitely helps. Thanks!

**Pull request merged**
