### PR TITLE
add Cargo.lock

### PR DESCRIPTION
**Pull request by marti1125**
Generated by Cargo

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks! Could you explain why this file needs to be ignored? If as the name suggests this is something like ruby's `Gemfile.lock` then it might not be a good idea to ignore it.

**Comment by marti1125** [comment]
the reason is after run $ cargo build
it will generate automatic Cargo.lock with this content:

[root]
name = "hello_world"
version = "0.0.1"

**Comment by arcresu** [comment]
Ok, but I assume that this isn't a completely arbitrary file. What is it intended to do?

**Comment by marti1125** [comment]
this can help :D
https://github.com/rust-lang/cargo/issues/315

**Comment by arcresu** [comment]
From the [documentation linked](http://doc.crates.io/guide.html#cargo.toml-vs-cargo.lock) to from the PR you mentioned, it seems that you definitely _do_ want to check this file in unless you're working on a library. I think maybe a better change would be to add the rule commented out with a note to uncomment it if you're developing a library.

**Comment by shiftkey** [comment]
@marti1125 unfortunately this isn't mergeable currently, and there are some questions outstanding which we'd like to clarify before merging :cry:

I need to clean up stale pull requests at some stage, and will close this out if I don't hear anything before **Friday 26th February**.

**Comment by shiftkey** [comment]
Nevermind, this has already been incorporated: https://github.com/github/gitignore/blob/master/Rust.gitignore#L13-L15

**Comment by marti1125** [comment]
ok :D :+1:

**Pull request closed without merging**
