### PR TITLE
Windows Azure Emulator

### PR DESCRIPTION
**Pull request by m1stegmann**
If you start Windows Azure Emulator a Directory "ecf" is created.

### CODE REVIEW

**Comment by shiftkey** [comment]
@m1stegmann do you have a link to a resource which explains this further?

**Comment by m1stegmann** [comment]
Directory before starting emulator the first time:

Directory: C:\temp\AzureCloudService1\AzureCloudService1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/1/2015   9:16 AM                bin
d-----         9/1/2015   9:16 AM                WorkerRole1Content
-a----         9/1/2015   9:16 AM           3014 AzureCloudService1.ccproj
-a----         9/1/2015   9:16 AM            144 AzureCloudService1.ccproj.user
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Cloud.cscfg
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Local.cscfg
-a----         9/1/2015   9:16 AM            428 ServiceDefinition.csdef


And after starting the Emulator:

Directory: C:\temp\AzureCloudService1\AzureCloudService1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/1/2015   9:16 AM                bin
d-----         9/1/2015   9:19 AM                csx
d-----         9/1/2015   9:19 AM                ecf
d-----         9/1/2015   9:19 AM                obj
d-----         9/1/2015   9:19 AM                rcf
d-----         9/1/2015   9:16 AM                WorkerRole1Content
-a----         9/1/2015   9:16 AM           3014 AzureCloudService1.ccproj
-a----         9/1/2015   9:16 AM            144 AzureCloudService1.ccproj.user
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Cloud.cscfg
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Local.cscfg
-a----         9/1/2015   9:16 AM            428 ServiceDefinition.csdef

There are two new folders: “efc” and “rfc” not included in the Visual Studio .gitignore (I missed the “rfc” folder in my commit…
The folders “bin”, “csx”, and “obj” are already ignored.

Von: Brendan Forster [mailto:notifications@github.com]
Gesendet: Dienstag, 1. September 2015 08:23
An: github/gitignore <gitignore@noreply.github.com>
Cc: Michael Stegmann <stegmann@noxum.com>
Betreff: Re: [gitignore] Windows Azure Emulator (#1642)


@m1stegmann<https://github.com/m1stegmann> do you have a link to a resource which explains this further?

**Comment by shiftkey** [comment]
> I missed the “rfc” folder in my commit…

If you could also include that I'll then take it in...

**Comment by shiftkey** [comment]
Closing in favour of #1647

**Pull request closed without merging**
