### PR TITLE
Update R.gitignore

### PR DESCRIPTION
**Pull request by Engcompaulo**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
@Engcompaulo any links to StackOverflow discussions or other documentation about this change?

**Comment by Engcompaulo** [comment]
I am requesting this modification because as I work in the area, I see many colleagues and other works here in Github itself, uploading files that should not be shared. As for example, bases in csv, feather, fst, and so on.

**Comment by shiftkey** [comment]
@Engcompaulo I want to ensure that this change makes sense to the community, because there might be other situations where users want to commit these files in the repository.

Any other information to help me understand this change would be greatly appreciated.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@Engcompaulo if you're still interested in submitting this contribution, please open a fresh pull request and address the outstanding questions from this review.

**Pull request closed without merging**
