### PR TITLE
Commented lines that is not commented.

### PR DESCRIPTION
**Pull request by Lordpeara**
I think that lines are comments, not ignores obviously.

### CODE REVIEW

**Comment by shiftkey** [comment]
I believe these are expected to be uncommented, but there's not much detail in the original PR https://github.com/github/gitignore/pull/1015

**Comment by Lordpeara** [comment]
Thanks. I wondered gitignore supports name with spaces

**Comment by shiftkey** [comment]
@Lordpeara I'm kinda indifferent to it - the `\` is generally used to escape special characters like `#` and `!` if the rule needs to use them - spaces aren't really special here...

**Comment by Lordpeara** [comment]
Thanks for review!

**Pull request closed without merging**
