### PR TITLE
Add .vscode folder

### PR DESCRIPTION
**Pull request by DillonB07**
**Reasons for making this change:**

_VSC is, in my opinion, the best editor. However, the `.vscode` doesn't need to be added into a repo._

### CODE REVIEW

**Comment by eightsixnine** [comment]
Hi  @DillonB07 

There is a separate gitignore for VS Code.

Here's a link:
https://github.com/github/gitignore/blob/main/Global/VisualStudioCode.gitignore

**Comment by DillonB07** [comment]
I understand that, but separate gitignores for specific IDEs aren't helpful. If you're just cloning a repo to make a quick fix you don't want IDE specific stuff in there.

Also, if I know most developers don't really want to be messing around with combining gitignores in a project.

**Comment by eightsixnine** [comment]
I've personally used several gitignore files for different languages and they are all language-specific, there are no OS or IDE files.

Look at Node.js, Java, C and so on.

I guess there is a reason why they make it like this, but who knows :)

**Comment by DillonB07** [comment]
Wait, you can have multiple gitignores in one repl? I thought you only had one called `.gitignore`. That makes a lot more sense now, thanks!

**Comment by eightsixnine** [comment]
Well, not multiple files, a single file, but nothing stops you from combining multiple files into one.

Or making your own gitignore file. This is just a plain-text file with your preferences. And this repo is just a template with those preferences, you may use it as you wish :)

**Pull request closed without merging**
