### PR TITLE
delete some extra rules for Qt-VS-add-in

### PR DESCRIPTION
**Pull request by AlexiaChen**
`GeneratedFiles/` - This is a folder generated by [Qt VS add-in](http://doc.qt.io/vs-addin/).
- moc,qrc,ui files are all under this folder

### CODE REVIEW

**Comment by shiftkey** [comment]
@AlexiaChen it looks like there's still a merge conflict against this branch.

Also, could you add some details about the QT add-in to the description so that others can understand this change?

**Comment by AlexiaChen** [comment]
@shiftkey  OK ,I updated the description of this PR

**Comment by shiftkey** [comment]
@AlexiaChen there's still a merge conflict here - possibly due to another branch appending to the file like you've done. Here's [a guide](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/) on understand what's happening and how to resolve it.

**Comment by shiftkey** [comment]
Closing due to inactivity.

**Pull request closed without merging**
