### PR TITLE
Add `*.sar` to Java.gitignore

### PR DESCRIPTION
**Pull request by bl-ue**
I've seen them before.  References:
- https://docs.jboss.org/jbossas/docs/Server_Configuration_Guide/4/html/ch02s01.html
- https://forum.step.esa.int/t/sar-files-in-java-8/5074

### CODE REVIEW

**Comment by drothmaler** [comment]
While I‘ve never encountered them myself, It sounds reasonable to me :-)

**Comment by bdougie** [comment]
Bey @bl-ue, can you provide more context on what is a .sar file and when it is created. Despite @drothmaler's approval, their response gives me low confidence that this is needed

**Comment by bl-ue** [comment]
@bdougie, from that jboss.org page that I linked, it says:

>The SAR application archive (e.g., **myservice.sar**) packages a JBoss service in a JAR file. It is mostly used by JBoss internal services.

Is that not enough?

**Comment by bl-ue** [comment]
@bdougie `.sar` is the only one of the `.*ar` Java ZIP-based archives that are not ignored in this file.

**Pull request closed without merging**
