### PR TITLE
update  Maven.gitignore file

### PR DESCRIPTION
**Pull request by caichuibin**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:** 

_TODO_

If this is a new template: 

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
Please fill out the template.

Without more context so I can properly review the changes, I can't accept this PR.

**Comment by drothmaler** [comment]
This seems like a big bundle of mixed gitignore rules. I see Ellipse, IntelliJ (Jetbrains), Gradle and SublimeText (all of those have an own gitignore file already) and a few other general rules...
The only actually Maven related rule I can spot is `dependency-reduced-pom.xml` - that seems to be related to the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html).

**Comment by drothmaler** [comment]
@the-redback why did you approve this???? Did you even look at the changes??

**Comment by the-redback** [comment]
My Bad. I was checking if anyone is authorized to approve. But, once I did, I could not undone it. 
Please skip my approval. Again I am sorry about this.

**Pull request closed without merging**
