### PR TITLE
Added Genero 4gl .gitignore

### PR DESCRIPTION
**Pull request by CptDarling**
Added support for Genero 4gl.

See http://4js.com/products/

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks, but could you provide some links to documentation to support the specific rules you're proposing?

**Comment by CptDarling** [comment]
Documentation for the Genero product can be found here, specifically the compiler output: http://www.4js.com/online_documentation/fjs-fgl-manual-html/?path=fjs-fgl-manual#c_fgl_FileExtensions_001.html

The Genero product is built on top of the older IBM 4gl product.  Documentation can be found here: http://publib.boulder.ibm.com/epubs/pdf/ct1vbna.pdf
Pages 1-6 and 1-47 detail some of the compiler outputs.

I can provide the documentation in pdf files if the links above are not available.

I have updated my commit with references to the documentation and added a few more files to the ignore list.

**Comment by CptDarling** [comment]
Have I provided enough information?

**Comment by shiftkey** [comment]
I'm going to close this out because the value of maintaining a template like this in the repository isn't clear to me.

@CptDarling if you feel like this should still be a template listed here, please read the section about [specialized templates](https://github.com/github/gitignore#specialized-templates) and open a new pull request that follows the new pattern.

**Pull request closed without merging**
