### PR TITLE
[Maven] fix comment

### PR DESCRIPTION
**Pull request by tjkemper**
The ! prefix will unignore the file.

**Reasons for making this change:**

The comment was misleading.

**Links to documentation supporting these rule changes:** 

N/A

If this is a new template: 

N/A

### CODE REVIEW

**Comment by dckg** [comment]
i find 'exclude' more appropriate

**Comment by shiftkey** [comment]
After thinking about this for a while, I'm not sure either term is better. I like this example from the Gradle template:

```
# Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
!gradle-wrapper.jar
```

**Comment by tjkemper** [comment]
@shiftkey made change as per your suggestion.

**Comment by shiftkey** [comment]
@tjkemper thanks!

**Pull request merged**
