### PR TITLE
[Python] .gitignore

### PR DESCRIPTION
**Pull request by okongwu101**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
@okongwu101 any links to StackOverflow discussions or other documentation about this change?

**Comment by shahid1579** [comment]
How to ignore the part of pom.xml file i.e i want to ignore the contents of <build> tag

**Comment by Coeur** [comment]
- No effort to support this PR with sources
- Excluding an arbitrary SQL language (postgresql) and not the many others when the language at hands here (Python) has no obvious relation to it
- Deleting the source of your pull request as seen by the `from unknown repository`, preventing any potential correction to it

3 reasons to reject this pull request.

**Comment by shiftkey** [comment]
@Coeur agreed

@okongwu101 please open a fresh pull request with more context if you still wish to see this change landed

**Pull request closed without merging**
