### PR TITLE
Ignore SQLite files

### PR DESCRIPTION
**Pull request by greystate**
This is an updated template for [Umbraco-CMS](https:://github.com/Umbraco/Umbraco-CMS) based on this conversation:

Screenshot 2022-05-06 at 11 30 49

### CODE REVIEW

**Comment by Username210** [comment]
Im sorry (◕ᴥ◕) dont hackme

**Comment by Gregory5555** [comment]
I pray to God I'm f****** find you and kill you I swear to God I'm a f****** kill you

**Comment by Gregory5555** [comment]
It it's all right I'll ask King Charles to find you my cousin and when he do you better hope and pray to God he don't get to you

**Comment by Username210** [comment]
Im praying for your vocabulary

error;404:filedownloading

**Review by Sum1cares — APPROVED** [review]

**Pull request merged**
