### PR TITLE
Update visualstudio.gitignore

### PR DESCRIPTION
**Pull request by arindamnayak**
Added *.sql file to include for # SQL Server files section.

### CODE REVIEW

**Comment by arindamnayak** [comment]
@arcresu , I have added one more file type for visual studio type projects, [This MSDN link] (https://msdn.microsoft.com/en-us/library/ms171969(v=vs.90).aspx) explains, how these files can be created in such projects. gitignore should ignore such file types. So I have changed this file and created pull request.

**Comment by shiftkey** [comment]
@arindamnayak I'm not clear on where in that link it explains *why* the file should be ignored. Also, this impacts everyone who creates `*.sql` files, not just those generated by Visual Studio.

**Comment by arindamnayak** [comment]
@shiftkey , my intention was to ignore those created by VS, since it will also ignore those SQL files , custom created ( now, I realize this), so we I taking the pull request back. We can close this. Sorry, for making confusion here.

**Comment by shiftkey** [comment]
@arindamnayak no problem!

**Pull request closed without merging**
