### PR TITLE
Update VisualStudio.gitignore

### PR DESCRIPTION
**Pull request by kratochviljan**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
@kratochviljan any links to StackOverflow discussions or other documentation about this change?

**Comment by sorashi** [comment]
[Looks like](https://www.visualmicro.com/page/Extending-Visual-Studio-Intellisense.aspx) the `__vm/` folder contains custom intellisense extensions for Visual Studio, which is something that should be in version-controlled imo.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@kratochviljan if you're still interested in submitting this contribution, please open a fresh pull request and address the outstanding questions from this review.

**Comment by mirh** [comment]
I'm not really sure how much fundamental/needed/useful the optional header file (or [friends](https://github.com/ngfelixl/FreeRC/blob/master/Nano/__vm/.Nano.vsarduino.h)) could be... but aside of that single one ([if even](https://www.visualmicro.com/forums/YaBB.pl?num=1498973678/1)) everything else [sounds](https://www.visualmicro.com/forums/YaBB.pl?num=1464921586/1) very [much](https://www.visualmicro.com/forums/YaBB.pl?num=1534974765) avoidable. 
Like, to be sure you don't want to save/send/upload your COM settings.

**Pull request closed without merging**
