### PR TITLE
Added SPFx (SharePoint Framework) gitignore

### PR DESCRIPTION
**Pull request by Tanddant**
**Reasons for making this change:**

Adding this to help others

**Links to documentation supporting these rule changes:**

This is the default gitignore added by the Microsoft SPFx project generator

If this is a new template:

 - **[Link to application or project’s homepage](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)**

### CODE REVIEW

**Review by martinwoodward — APPROVED** [review]
Approved with change into community folder

**Comment by Bnjffe67899** [comment]
How ahrew lam Hridoy

**Comment by Bnjffe67899** [comment]
Work

**Comment by Tanddant** [comment]
I'm sorry @Bnjffe67899 - I'm not sure what you mean? 😊

**Pull request merged**
