### PR TITLE
New

### PR DESCRIPTION
**Pull request by irshadpc**
**Reasons for making this change:**
.xccheckout file conflict with different systems.

**Links to documentation supporting these rule changes:** 

http://stackoverflow.com/questions/18340453/should-xccheckout-files-in-xcode5-be-ignored-under-vcs

### CODE REVIEW

**Comment by shiftkey** [comment]
@irshadpc as part of #1546 it was suggested that `*.xcuserstate` sits under the `xcuserdata` folder, meaning the rule wasn't necessary.

That SO thread pre-dates this PR and talks about XCode 5, so I'd love to understand more about which answer is more accurate today...

**Comment by irshadpc** [comment]
@shiftkey the above context got issue with me and my colleagues.

**Comment by irshadpc** [comment]
@shiftkey i understood the context ,thanks for comment.

**Comment by shiftkey** [comment]
Closing in favour of #2163

**Pull request closed without merging**
