### PR TITLE
add python on git ignore python

### PR DESCRIPTION
**Pull request by JasonJafari**

### CODE REVIEW

**Comment by wyz23x2** [comment]
`.pyi` could be added too.

**Comment by Aziz-prog** [comment]
'''python'''

**Comment by simaki** [comment]
Thank you @JasonJafari .

I'm afraid PyCharm specific files are already covered by [Global/JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore).

**Comment by bdougie** [comment]
Closing in favor of https://github.com/github/gitignore/pull/3451

**Pull request closed without merging**
