### PR TITLE
Add bower_components to VisualStudio.gitignore

### PR DESCRIPTION
**Pull request by Zenuka**
Added bower_components to .gitignore to not include bower packages: http://bower.io/

### CODE REVIEW

**Comment by shiftkey** [comment]
This was removed in #1529 and I'd love @sayedihashimi to chime in here about why he proposed that

**Comment by shiftkey** [comment]
Oh, and @barrytang

**Comment by sayedihashimi** [comment]
I just made the commit the decision was made by @damianedwards and @mkristensen, they should reply with more info.

**Comment by Zenuka** [comment]
Ah, didn't search enough, my bad... Maybe we could add it commented out?

**Comment by shiftkey** [comment]
@Zenuka I'd like that

**Comment by Zenuka** [comment]
@shiftkey, done

**Comment by shiftkey** [comment]
I'm letting this sit until **Friday 19 February AEDST** for feedback.

**Comment by Haacked** [comment]
:+1: to merging this.

**Comment by shiftkey** [comment]
Oops, missed my self-imposed deadline. Let's take this in and see what other feedback comes up.

**Pull request merged**
