### PR TITLE
Stop tracking of VS vshost files

### PR DESCRIPTION
**Pull request by chuckleplant**
Visual Studio generates vshost files automatically, these are not to be tracked.

### CODE REVIEW

**Comment by shiftkey** [comment]
I'm curious why this isn't being caught as part of the previous rules in this section - could you tell me a bit about the problem you're seeing?

**Comment by chuckleplant** [comment]
C# console projects for instance generate these within the solution folder. And they're not ignored in the .gitignore file. As far as I understand these are helper files to launch debugging from VS. However they are automatically generated, like the user and database files. 
Shouldn't these be ignored?

**Comment by shiftkey** [comment]
cc @davkean for :eyes: on whether this should be captured in the gitignore template

**Comment by davkean** [comment]
What do you mean by VS generates them in the solution folder? These should be getting generated in bin directory, and already covered by gitignore.

**Comment by chuckleplant** [comment]
Hi there, this is a bit old but maybe in my project those were redirected somewhere else.. can't tell for sure. In any case those should always be ignored even if user selects a different generation folder.

**Comment by shiftkey** [comment]
Closing this one out as unclear. Please reopen if a better repro of this is happening - [VSHost is going away](https://github.com/dotnet/roslyn-project-system/issues/66#issuecomment-269733749) in the future anyway...

**Pull request closed without merging**
