### PR TITLE
Qt: typo fix and extra empty lines removal

### PR DESCRIPTION
**Pull request by davidebeatrici**
**Reasons for making this change:**

6d6dce75f8ec06bcd18e6fbceb9c2278a32f23a8: To keep consistency with other files in the repository, which all appear to have a single empty line at the end of them and no empty lines under comments.

1bee1a16dcfa60097115eac1dfce82b22fbd0645: The name of the program is **Qt Creator**.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
I would also remove these empty lines:
https://github.com/github/gitignore/blob/f9a44f6c36d9fdd66a1aa9610f1331fdabf5e32c/Qt.gitignore#L2
https://github.com/github/gitignore/blob/f9a44f6c36d9fdd66a1aa9610f1331fdabf5e32c/Qt.gitignore#L14
https://github.com/github/gitignore/blob/f9a44f6c36d9fdd66a1aa9610f1331fdabf5e32c/Qt.gitignore#L38

**Comment by shiftkey** [comment]
> I would also remove these empty lines:

@davidebeatrici go for it

**Comment by davidebeatrici** [comment]
@shiftkey Done.

**Comment by shiftkey** [comment]
@davidebeatrici thanks!

**Comment by davidebeatrici** [comment]
@shiftkey You're welcome!

**Comment by josephkaram1986** [comment]
????

**Pull request merged**
