### PR TITLE
Add the other Dreamweaver added files

### PR DESCRIPTION
**Pull request by photodude**
Depending on user configuration Dreamweaver might add more files. This PR addresses the added files and folders I know about.

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks for this. Could you provide some links to documentation describing these files, or if there is none, then could you provide examples and/or explain why they should be ignored?

**Comment by photodude** [comment]
I discovered these files as I made changes to a Dreamweaver (DW) configuration for a project
Here is an explanation with links were I could find some documentation:

File, Folder, or file type | Use or explanation
------------ | -------------
| [dw_php_codehinting.config](http://www.quepublishing.com/articles/article.aspx?p=1588847&seqNum=17) | created when PHP code hinting is enabled in DW | 
|  [*.mno](http://www.file-extensions.org/mno-file-extension) | file contains design notes for DW usually in the `_notes` folder. Sometimes this file still shows in the git changes list |
| [_compareTemp](https://books.google.com/books?id=33nCaLfjB_8C&pg=PA365&lpg=PA365&dq=dreamweaver+_compareTemp+folder&source=bl&ots=c9R-Y1geRp&sig=3y10KTBpOGbWa7_LYiJjHcbdC3M&hl=en&sa=X&ved=0CCAQ6AEwAGoVChMI0MjcmsjdxgIVzjWICh0RpQZV#v=onepage&q=dreamweaver%20_compareTemp%20folder&f=false) | A Folder created when a File compare is used from DW |
| configs | a folder created depending on some DW configuration settings for a project |
| [web.configs](https://books.google.com/books?id=xlC-v1R2YiAC&pg=PA519&lpg=PA519&dq=dreamweaver+project+configs+folder&source=bl&ots=v33VJuPh_m&sig=NbNg_psoTdqup-Ps_rvsUf6qxlE&hl=en&sa=X&ved=0CGQQ6AEwCWoVChMI972Lj8ndxgIVDaOICh1XAgBv#v=onepage&q=dreamweaver%20project%20configs%20folder&f=false) | a file created after a connection to a database is established |

**Comment by vgturtle127** [comment]
@arcresu Can we merge this?

**Comment by shiftkey** [comment]
:thumbsup: thanks for the contribution @photodude!

**Comment by photodude** [comment]
You are welcome. Thanks for the merge.

**Pull request merged**
