### PR TITLE
Adds Support for Modern IDEs

### PR DESCRIPTION
**Pull request by addiittya2006**
Adds support for Auto-generated files for Modern IDE's like Appcode, Pycharm,
RubyMine, Intellij, Netbeans, Eclipse etc.

### CODE REVIEW

**Comment by addiittya2006** [comment]
Highly Important for Modern day ides

**Comment by addiittya2006** [comment]
Due to slow Internet Connections clicked the wring buttons.

**Comment by shiftkey** [comment]
Check out the [Global](https://github.com/github/gitignore/tree/master/Global) folder for existing `Eclipse`, `JetBrains` and `NetBeans` templates. If you have rules that don't exist in those, please add them there.

The `Django` rules should be added to the `Python` template.

**Comment by addiittya2006** [comment]
Already Up-to-Date

**Pull request closed without merging**
