### PR TITLE
Add Vagrant Logs to Exclude List

### PR DESCRIPTION
**Pull request by utkonos**

### CODE REVIEW

**Comment by shiftkey** [comment]
@utkonos any links to StackOverflow discussions or other documentation about this change?

**Comment by utkonos** [comment]
@shiftkey Definitely! Here is the official vagrant documentation for debugging and troubleshooting that mentions this log file:
https://www.vagrantup.com/docs/other/debugging.html

**Comment by shiftkey** [comment]
@utkonos this seems to be a user-specified file rather than something generated by vagrant itself, so I'm not sure how useful this will be. Many other templates will just ignore `*.log` files as well, which might be more useful here (along with a comment).

**Comment by utkonos** [comment]
I will submit a new pull request with the suggested adjustments.

**Pull request closed without merging**
