### PR TITLE
[Xcode/ObjC/Swift] Fix path to xcuserdata directory for Xcode project

### PR DESCRIPTION
**Pull request by nnsnodnb**
**Reasons for making this change:**

"xcuserdata" is not ignore.

### CODE REVIEW

**Comment by shiftkey** [comment]
@nnsnodnb any links or documentation explaining this change?

**Comment by nnsnodnb** [comment]
@shiftkey Sorry.
I think these links can explain the change.
- http://stackoverflow.com/questions/6564257/cant-ignore-userinterfacestate-xcuserstate
- http://stackoverflow.com/questions/15646107/gitignore-for-everything-inside-the-xcuserdata-folder-does-not-ignore-an-xcuser

**Comment by andy1247008998** [comment]
I don't know why this PR is not merged but it works perfect.
@nnsnodnb Thanks a lot!

**Comment by shiftkey** [comment]
@nnsnodnb @andy1247008998 unless I'm missing something, those links suggest the expression should be `*.xcodeproj/project.xcworkspace/xcuserdata`...

**Comment by andy1247008998** [comment]
@shiftkey A workspace has one or more projects, so `*.xcodeproj/xcuserdata/` is correct.
You can further add `*.xcworkspace/xcuserdata/` to ignore user data files inside a workspace.

**Pull request closed without merging**
