### PR TITLE
Packer template - Exclude .pkrvars.hcl files

### PR DESCRIPTION
**Pull request by tlindsay42**
**Reasons for making this change:**

Starting from version 1.5.0, Packer supports HCL2 definition files. These files serve the same purpose as Terraform `.tfvars` files, which persist variable values and are likely to contain sensitive data such as password, private keys, and other secrets.

[Citation](https://www.packer.io/guides/hcl/variables#from-a-file)

> We don't recommend saving usernames and password to version control, but you can create a local secret variables file and use -var-file to load it.

**Links to documentation supporting these rule changes:**

* https://www.packer.io/guides/hcl
* https://www.packer.io/guides/hcl/variables#from-a-file

### CODE REVIEW

**Comment by tlindsay42** [comment]
Ready for review @shiftkey

**Review by 53jk1 — APPROVED** [review]

**Comment by tlindsay42** [comment]
@53jk1, do you have sufficient access to merge? I don't. ?

Or @bdougie?

**Comment by 53jk1** [comment]
No, I haven't

**Review by bdougie — APPROVED** [review]

**Comment by tlindsay42** [comment]
Thanks @53jk1 & @bdougie!

**Pull request merged**
