### PR TITLE
gitignore for laravel5 and lumen

### PR DESCRIPTION
**Pull request by jerodev**
Created lumen gitignore
Created laravel5 gitignore compatible with the new folder structure.

### CODE REVIEW

**Comment by shiftkey** [comment]
Is there a reason why the existing Laravel file cannot be used?

https://github.com/github/gitignore/blob/master/Laravel.gitignore

**Comment by jerodev** [comment]
i thought it would be better to create a new one because Laravel5 has an entire different folder structure compared to Laravel4.

But indeed, it would be possible to merge them. I will create another commit.

**Comment by shiftkey** [comment]
@jerodev would it be worth grouping the new rules - the ones specific to Laravel 5 - together to help users understand which ones they should care about?

**Comment by shiftkey** [comment]
Also, I'm not familiar with this Lumen project - could you tell me a bit about that and where those rules have come from?

**Comment by jerodev** [comment]
@shiftkey Lumen is a php micro framework. It is actualy a stripped down version of Laravel. http://lumen.laravel.com/

I have removed the lumen gitignore because actualy the folder structure from Laravel5 and Lumen is almost the same and the rules work for both frameworks. I have also added comments to let the users know what rules are for wich version.

**Comment by shiftkey** [comment]
@jerodev that's great, thanks!

**Comment by shiftkey** [comment]
Let me know when this is ready to review - it looks close!

**Comment by jerodev** [comment]
@shiftkey I have tested the gitignore with both a Laravel5 and a Lumen project, and it works great!

**Pull request merged**
