### PR TITLE
Ignoring: Android Studio local files

### PR DESCRIPTION
**Pull request by gbazilio**

### CODE REVIEW

**Comment by hiralin** [comment]
+1

**Comment by ryanseys** [comment]
Easier to just ignore:

```
.idea
*.iml
```

But yes, I agree that Android Studio should be added to the ignored files.

**Comment by arcresu** [comment]
Thanks, but this is why we have `Global/JetBrains.gitignore`

**Comment by ryanseys** [comment]
I'd suggest also having these in Android Studio considering they come with the default .gitignore that Android Studio creates.

**Comment by arcresu** [comment]
The `Global/` rules are intended to go in your global ignore file so that you wouldn't have to add them in each project. That's the way we've divided up this repository.

**Pull request closed without merging**
