### PR TITLE
Create Batch.gitignore

### PR DESCRIPTION
**Pull request by jtrent238**
**Reasons for making this change:**

Added Batch

**Links to documentation supporting these rule changes:** 

_TODO_

If this is a new template: 
- **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
@jtrent238 can you tell me a bit about the motivation for adding this template?

**Comment by jtrent238** [comment]
@shiftkey I use a lot of batch in my project so this could be helpful, and some other people might find it helpful also.

**Comment by Arinerron** [comment]
@shiftkey I +1 this

**Comment by Arinerron** [comment]
(though I am a Linux user)

**Comment by gautamkrishnar** [comment]
@jtrent238  i am not sure about this. you are actually ignoring the batch script file. Why do you need to ignore that files?

**Comment by gautamkrishnar** [comment]
If you are sure about this then don't forget to add the extensions like :  .`*.cmd` and `*.btm`

**Comment by stephengroat** [comment]
Ignoring Batch files is ignoring the source files if you're a batch programmer (I've had to do some of it, it's rough)

I think that ignoring specific auto-generated batch files is more appropriate for auto-generated batch files from a specific build system or IDE, rather than a separate template

**Comment by shiftkey** [comment]
Closing this out because it doesn't seem clear what problem this template is solving...

**Pull request closed without merging**
