### PR TITLE
Adding pdfcomment.sty auxiliary files

### PR DESCRIPTION
**Pull request by habi**
From https://github.com/wspr/latex-auxfiles

### CODE REVIEW

**Comment by shiftkey** [comment]
:cry: merge conflicts

**Comment by habi** [comment]
How can I resolve that conflict if I don't have write access to the repository?
Shall I delete the pull request and submit a new one?

**Comment by shiftkey** [comment]
@habi the change was made in your fork of this repo, so you can

To bring your fork up to date with whatever is currently upstream:

```
git remote add github https://github.com/github/gitignore.git -f
git checkout master
git reset github/master --hard
```

Then try merging `master` into your branch with this change:

```
git checkout patch-2
git merge master
```

That should show you the merge conflict. Then you can make the change and push the result back to this branch:

```
git push origin patch-2
```

**Comment by habi** [comment]
Thanks for the clear instructions.
I just did that, which fixed the merge conflict.

**Pull request closed without merging**
