### PR TITLE
Add ToadExtension plugin to Eclipse.gitignore

### PR DESCRIPTION
**Pull request by macik**
https://www.toadworld.com/products/toad-extension-for-eclipse

Toad Extension creates `.teeproject` files with SQL connection specific settings in the root of the Exlipse project.

### CODE REVIEW

**Comment by shiftkey** [comment]
Do you have a link to where this rule is documented by the tool? I'd love to be able to point users to a canonical source if they have questions about this PR.

**Comment by shiftkey** [comment]
@macik unfortunately this isn't mergeable currently, and there are some questions outstanding which we'd like to clarify before merging :cry:

I need to clean up stale pull requests at some stage, and will close this out if I don't hear anything before **Friday 26th February**.

**Comment by macik** [comment]
Thank you for your answer. I'll try to provide requested info till specified date.

**Comment by macik** [comment]
They promised that `.teeproject` is gone away from next release, so…
just for information:
http://www.toadworld.com/products/toad-extension-for-eclipse/f/42/t/27291

**Comment by shiftkey** [comment]
@macik thanks for the update!

**Pull request closed without merging**
