### PR TITLE
Add ignoring editors files

### PR DESCRIPTION
**Pull request by Z4RX**

### CODE REVIEW

**Comment by bl-ue** [comment]
Please remove `.vscode`.  See https://github.com/github/gitignore/pull/3661#issuecomment-787093820

**Comment by Z4RX** [comment]
Probably Adding only necessary files is better solution?
```
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
```

**Comment by bl-ue** [comment]
Hmm...well so far I've only seen `*.json` configuration files in `.vscode/`.  Are you seeing anything different?

**Comment by simaki** [comment]
Thank you!

I'm afraid these files do not have to be added because they are already included or supposed to be included in
* [Global/JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)
* [Global/VisualStudioCode.gitignore](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore)

**Pull request closed without merging**
