### PR TITLE
Ruby: Ignore .env

### PR DESCRIPTION
**Pull request by elifoster**
**Reasons for making this change:**

This file is used moderately commonly to store environment variables locally. I often find myself adding it to the Ruby gitignore manually in my Ruby applications.

**Links to documentation supporting these rule changes:** 

The Python gitignore ignores the same file for the same reason. And before the fact that this file is only used when the dotenv gem is also used, that is the same with Python.

### CODE REVIEW

**Comment by shiftkey** [comment]
For reference, here's a note about this from the `dotenv` README https://github.com/bkeepers/dotenv#should-i-commit-my-env-file

**Comment by shiftkey** [comment]
@elifoster putting aside what we did with the Python template, this comment is interesting:

> Personally, I prefer to commit the .env file with development-only settings. This makes it easy for other developers to get started on the project without compromising credentials for other environments.

**Comment by elifoster** [comment]
Hm, that's interesting. I've never had a need for the .env file to be pushed to version control. Maybe it could be default commented out like many of the other rules in this template?

**Comment by shiftkey** [comment]
> Maybe it could be default commented out like many of the other rules in this template?

I like this idea

**Comment by elifoster** [comment]
I have commented it out. I figured it wasn't really necessary to explain what that file is for, as since it's commented out, it will probably only be used by people who know exactly what they are doing.

**Comment by shiftkey** [comment]
@elifoster what about a brief comment above the line explaining the file's purpose?

**Comment by elifoster** [comment]
@shiftkey There you go :)

**Comment by shiftkey** [comment]
@elifoster thanks!

**Pull request merged**
