### PR TITLE
Update Python.gitignore

### PR DESCRIPTION
**Pull request by vltr**
**Project:** pyenv - https://github.com/yyuu/pyenv
**Documentation:** The same link
**Why:** a lot of developers tend to use, either language with a lot of versions (or closed enviroment runtimes) a wrapper / software / language interpretor version management, which is the case of pyenv, one of the most used for Python. I'm creating this pull request because pyenv creates a file `.python-version` if you use local file configurations for your projects (please see [pyenv-local reference](https://github.com/yyuu/pyenv/blob/master/COMMANDS.md#pyenv-local) for more information).

*PS:* I'm not inserting `.pyenv-local` file to `.gitignore` because it is deprecated.

Thanks a lot :)

### CODE REVIEW

**Comment by shiftkey** [comment]
It's not clear to me from the docs whether this file should be ignored by default. A similar example that comes to mind is how Ruby has version switchers like `chruby` and `rbenv` - these look for a file named `.ruby-version` in your repository directory.

The default gitignore for Ruby documents this, but leaves it commented out, so users can opt-in to ignoring this: https://github.com/github/gitignore/blob/master/Ruby.gitignore#L32

Does "opt-in" feel like a more suitable option here? I'm under the impression that library or application authors would like to associate their codebases with a specific version of Python, but I'm not so familiar with the Python ecosystem as a whole...

**Comment by vltr** [comment]
@shiftkey thanks for your review! A simple answer is yes, it could be a opt-in, since there's a lot of others version switchers for Python. I bringed pyenv up because it has some more advanced usage - see the [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenvwrapper) plugin.

In the other hand - a spin off this conversation - I do feel like the `.rvmrc` file from Ruby [have the exact behaviour](https://rvm.io/workflow/rvmrc) when using pyenv with virtualenvwrapper plugin (section "Project (project_directory/.rvmrc)"), where you can create an entire set of Python,  including a whole world of differente packages installed (more like rvm's gemset). So ... That brings me the question: [why is it not an opt-in](https://github.com/github/gitignore/blob/master/Ruby.gitignore#L36) like `.ruby-version`?

Thanks a lot! :)

**Comment by vltr** [comment]
Well ... If you (or anyone) wanted a reason why this should be in the Python.gitignore, I think I may have bumped into the answer.

I was seeking for a code editor that could "fill the gaps" that I have with ST3. Atom looks like a good choice, since one of my colleagues uses it. Ok, then I download the AUR package and try to install it in my machine (Arch Linux User Repository). Somewhere while installing, it crashes:

```
==> Starting build()...
Node: v5.3.0
npm: v3.5.2
Installing build modules...
WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"5.3.0","npm":"3.5.2"})
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/richard/.pyenv/shims/python2 -c import platform; print(platform.python_version());
gyp ERR! stack pyenv: version `2.7.6' is not installed (set by /home/richard/build/atom-editor/src/atom-1.3.2/.python-version)
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Linux 4.3.3-1-ck
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ...
```

So, WTF? Since when do I have Python 2.7.6 in my machine? Oh wait, `src/atom-1.3.2/.python-version`? That doesn't seems right! But, as I looked into the Atom git repository ... [There it is](https://github.com/atom/atom/blob/master/.python-version#L1)!! Sneaky bastard.

So OK, I can install Atom by hand and bla bla bla, but I do like pacman and wouldn't like to install packages with modified sources or SHA256 sums because of a file that **wasn't meant to be there**. Atom is for developers, as is pyenv. If a link between `.python-version` and `.gitignore` was needed, I think you should look no further.

Cheers!
Richard.

**Comment by shiftkey** [comment]
@vltr not to go too far sideways with this discussion, but it looks like there's an important reason for the `.python-version` file and they're discussing the best way forward to deal with the AUR packages in https://github.com/atom/atom/issues/7450

**Comment by vltr** [comment]
Well, this is a situation. My two cents are : either promote (and bundle) a
specific Python version to build Atom (I don't why am I arguing about this
anyway) OR be clear about it in any README or FAQ. Nothing wrong about
giving information. What is wrong, in this world, is not to give it. I' m
sorry if this looks too rispid.

Cheers,
Richard.

@vltr <https://github.com/vltr> not to go too far sideways with this
discussion, but it looks like there's an important reason for the
.python-version file and they're discussing the best way forward to deal
with the AUR packages in atom/atom#7450
<https://github.com/atom/atom/issues/7450>

—
Reply to this email directly or view it on GitHub
<https://github.com/github/gitignore/pull/1801#issuecomment-167003695>.

**Comment by nicktimko** [comment]
I'll copy-paste from the earlier closed PR:

> pyenv is a Python version manager for *nix shells. It allows the Python version and virtual environment to be set locally, per-directory, using a .python-version file. Because pyenv environment names are **arbitrary and machine+user-specific** (the name being in the .python-version file), they are usually noise.

Pyenv doesn't have a provision that says "make a Python environment with this name", but you manually have to say `pyenv virtualenv 2.7.11 oogabooga` or the like on each machine then fill it up with `pip install -r reqs.txt`.

**Comment by shiftkey** [comment]
@nicktimko thanks for that extra context. I wasn't aware of the arbitrariness of it that's available.

Given I'm not hearing anyone else push back on this change, I'm happy to merge this in. Unfortunately there's a merge conflict here preventing me from doing this /cc @vltr

**Comment by vltr** [comment]
@shiftkey @nicktimko thanks! There's the PR updated :)

**Comment by shiftkey** [comment]
@vltr great, and thanks for working through this with me!

**Comment by vltr** [comment]
@shiftkey no problem! I'm glad to help out! Cheers!! :)

**Pull request merged**
