### PR TITLE
Ignore ASP.Net 5 project.lock.json

### PR DESCRIPTION
**Pull request by Kagamine**
Ignore ASP.Net 5 project.lock.json

### CODE REVIEW

**Comment by shiftkey** [comment]
cc @davidfowl @eilon

**Comment by Eilon** [comment]
Hmm it's not necessarily wrong to check it in. For some projects it's the right thing to do because it allows easily locking dependencies. @davidfowl thoughts?

**Comment by Kagamine** [comment]
When the environment changed, the project.lock.json must be generated again, so I think we should ignore it.

**Comment by shiftkey** [comment]
Nevermind, I knew we already talked about this before https://github.com/github/gitignore/pull/1505

**Pull request closed without merging**
