### PR TITLE
ignore everything

### PR DESCRIPTION
**Pull request by was4444**
**Reasons for making this change:**

Someone like me may want to control all content that indexed.

Force all indexed content meaningfully.

### CODE REVIEW

**Comment by shiftkey** [comment]
This is cool and all, but I'd rather focus on supporting the existing ecosystem of languages and tools.

**Comment by was4444** [comment]
@shiftkey, is there any way to use private ``.gitignore`` templates in ``GitHub``.

**Comment by shiftkey** [comment]
@was4444 I don't understand the question. Could you elaborate?

**Comment by was4444** [comment]
@shiftkey, the question probably should not be asked here, but when create a new repo from ``GitHub``, we can select a ``.gitignore``, which seems must in this repo, to create as the initial commit. I just want to use my private ``.gitignore`` file as the initial commit.

**Pull request closed without merging**
