### PR TITLE
Ignore files generated by NuGet v3 project.json

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by AArnott** [comment]
CC: @davidfowl, @yishaigalatzer

**Comment by shiftkey** [comment]
We document some `project.json` rules on line 43 - should those changes be kept alongside these new changes?

**Comment by AArnott** [comment]
I was split on that. But it's not DNX related so I sided with keeping it with other nuget lines.

**Comment by shiftkey** [comment]
:cool: thanks!

**Pull request merged**
