### PR TITLE
Add .gitignore for the Clean programming language

### PR DESCRIPTION
**Pull request by dopefishh**
Clean is a lazy functional programming language developed on the Radboud University. In the development version Clean is bundled with the iTasks environment.
- Homepage clean: http://clean.cs.ru.nl
- Homepage iTasks: http://clean.cs.ru.nl/ITasks

### CODE REVIEW

**Comment by camilstaps** [comment]
Definitely seconded. Since GitHub already recognises *.icl and *.dcl as Clean files, this is a very useful addition.

**Comment by PimJager** [comment]
Yes, this would be very useful.

**Comment by KDercksen** [comment]
Great addition.

**Comment by dopefishh** [comment]
This is superseeded by PR #2303

**Pull request closed without merging**
