### PR TITLE
Adding *.log.*

### PR DESCRIPTION
**Pull request by alexburner**
This handles files such as "npm-debug.log.93119ca793e7808eafd004b0ba285cd2"

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks! Is this a new change to npm or the result of some other tool or something?

**Comment by shiftkey** [comment]
@alexburner unfortunately this isn't mergeable currently, and there are some questions outstanding which we'd like to clarify before merging :cry:

I need to clean up stale pull requests at some stage, and will close this out if I don't hear anything before **Friday 26th February**.

**Comment by alexburner** [comment]
Hey sorry for the inactivity. This is something I've encountered a few times over the past year but I don't have explanations or reliable steps for repro.

If no one else has seen npm-debug.log files with a hash appended and *.log.* causes controversy, no need to push it through.

I'll come back if I ever have a solid case.

**Comment by shiftkey** [comment]
@alexburner given there's a merge conflict here, I'm going to close this out rather than let it hang.

Do let me know if you encounter it again...

**Pull request closed without merging**
