### PR TITLE
AL Template for Dynamics 365 Business Central

### PR DESCRIPTION
**Pull request by acyvas**
Support for AL language projects for Microsoft Dynamics 365 Business Central
link [https://github.com/Microsoft/AL/](https://github.com/Microsoft/AL/)

### CODE REVIEW

**Comment by vxzry** [comment]
Hi, I was about to submit my own pull request when I saw yours. Could we use this `.gitignore` instead? I got it from [AL's official github repository](https://github.com/microsoft/AL/blob/master/.gitignore).
```
## --- AL gitignore ---
## Ignores generated binary files and 
## temporary files from Visual Studio and Visual Studio code

# Binary files
.alpackages/
*.app

# Temp files
.vs/
.vscode/

# Others
~$*
*~
```

**Comment by JeremyVyska** [comment]
@acyvas - Perhaps an update to include 

.alcache?

Otherwise, would love to get this into GH.

**Comment by bdougie** [comment]
Thanks for the contribution, however per the contribution guidelines this file should be placed in the community folder. Please edit the location of the file. Also, realize this is a late reply and https://github.com/github/gitignore/pull/3871 also exists.

https://github.com/github/gitignore#specialized-templates

**Comment by bdougie** [comment]
Closing in favor of https://github.com/github/gitignore/pull/3871

**Pull request closed without merging**
