### PR TITLE
include preamble files generated by mylatexformat package

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by shiftkey** [comment]
@Konfekt any reference material to help us understand why we should be ignoring these file extensions?

**Comment by Konfekt** [comment]
Hello, 

How about 

ftp://ftp.tex.ac.uk/ctan%3A/macros/latex/contrib/mylatexformat/mylatexformat.pdf

It is a file compiled from your TeX file preamble and as such reproducable from your source; around 10Mb big over here where the  source code weighs 10 Kb.

**Comment by Konfekt** [comment]
Hello,

Anything more detailed missing for this pull request to be reconsidered ?

**Comment by Konfekt** [comment]
Thank you!

**Pull request merged**
