### PR TITLE
Trim trailing whitespace

### PR DESCRIPTION
**Pull request by jayvdb**
**Reasons for making this change:**

Trailing whitespace is ugly.

**Links to documentation supporting these [rule] changes:** 

n/a

### CODE REVIEW

**Comment by shiftkey** [comment]
@jayvdb thanks!

**Comment by jayvdb** [comment]
@shiftkey , any chance we can add some CI to prevent regressions?
I've done the same at https://github.com/dvcs/gitignore/blob/master/.travis/check-whitespace.sh (enhanced at https://github.com/dvcs/gitignore/pull/117)

I'd be happy to implement it, ideally using Travis-CI, either raw .sh using `git`, or in any major scripting language which you prefer, provided it has a [wildmatch-like](https://libraries.io/search?keywords=wildmatch) library so that it can grow to check validity of rules and possibly also check inter-relations between rules.

**Comment by shiftkey** [comment]
@jayvdb I've enabled Travis with an example build that's now passing https://travis-ci.org/github/gitignore/builds/393575258 - feel free to build upon that

**Comment by susphir** [comment]
> **Reasons for making this change:**
> 
> Trailing whitespace is ugly.
> 
> **Links to documentation supporting these [rule] changes:** 
> 
> n/a
> 

> "**_a47c27d3517b7faa04e5332a37c869b2c857127b_"**
(-:

**Pull request merged**
