### PR TITLE
[Gradle] build rule should support subprojects

### PR DESCRIPTION
**Pull request by guilhermerigorecio**
The current form does not work with multiple subprojects.

### CODE REVIEW

**Comment by drothmaler** [comment]
Hm, but this way we would also ignore all other "build" folders (e.g. if one of your packages is: "com.company.project.build.tools"). So, I think we should at least unignore all `build` folders inside of "src/" folders...

**Comment by shiftkey** [comment]
I'm not sure whether a wildcard term will help or hinder here, as people like to organize their source code in different ways (there's already mentions of `src` and `buildSrc`).

Could we document this rule better to explain that it will only cover `build` at the root, and how to add additional rules to handle subproject scenarios?

**Comment by shiftkey** [comment]
Closing this out due to inactivity

**Comment by Baneeishaque** [comment]
What about this? @ @ @ @shiftkey

**Pull request closed without merging**
