### PR TITLE
Rename Magento.gitignore to Magento1.gitignore

### PR DESCRIPTION
**Pull request by Nolwennig**

### CODE REVIEW

**Comment by Nolwennig** [comment]
Because Magento1 and Magento2 have a very different folder structure.

In example, on Magento2 the folder vendor should be ignore by versionning. On Magento1 the folder vendor don't exist

**Comment by shiftkey** [comment]
@Nolwennig  apologies for the delay in replying to this.

I had a lot of these templates requested, but I couldn't quite figure out the right place for them. I ended up settling on #2857, and you'll see a Magento v1 template can now be found at `community/PHP/Magento1.gitignore`.

The current `Magento.gitignore` template should be for the latest version of Magento.

Feel free to submit any future improvements to that template, and thanks again for the contribution!

**Comment by Nolwennig** [comment]
Great !

Thanks @shiftkey

**Pull request closed without merging**
