### PR TITLE
Added ".idea/" for PyCharm

### PR DESCRIPTION
**Pull request by jieggii**
**Reasons for making this change:**

I added .idea/ folder to Python.gitignore because it contains only personal and sensitive informaiton 

**Links to documentation supporting these rule changes:**

https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks, but we have a shared [`Global\JetBrains.gitignore`](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore) for our template for JetBrains IDEs (including PyCharm).

**Comment by jieggii** [comment]
That's cool, but why don't you add it into repository creation menu?
image

**Comment by shiftkey** [comment]
@jieggii that's a separate area to the maintenance of these templates, and you'll have to speak to [GitHub Support](https://github.com/contact) about that feature.

**Comment by Baneeishaque** [comment]
try [gitignore.io](https://www.gitignore.io) @jieggii

**Comment by BrianMSheldon** [comment]
See #3451 for an optional solution

**Pull request closed without merging**
