### PR TITLE
Create ProgressABL.gitignore

### PR DESCRIPTION
**Pull request by patrickTingen**
**Reasons for making this change:**

New template for Progress ABL related projects

If this is a new template: 
- **Link to application or project’s homepage**: https://www.progress.com/ 

Ignore file for Progress ABL

### CODE REVIEW

**Comment by patrickTingen** [comment]
Is anything blocking this request from merging?

**Comment by patrickTingen** [comment]
... oops

**Comment by hmhka** [comment]
Is this merged as I cannot see it on the website or in the repo?

**Comment by patrickTingen** [comment]
Don't see it either, so my guess is that it is not merged

**Comment by bdougie** [comment]
Thanks for the contribution, however per the contribution guidelines this file should be placed in the community folder. Please edit the location of the file. 

https://github.com/github/gitignore#specialized-templates

**Pull request closed without merging**
