### PR TITLE
Added Ecplise and PyDev projects.

### PR DESCRIPTION
**Pull request by chamfay**

### CODE REVIEW

**Comment by shiftkey** [comment]
Any links to documentation to explain what these files are for, and why they can be safely ignored?

**Comment by chamfay** [comment]
[.project file](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fproject_description_file.html)

**Comment by stephengroat** [comment]
Both of your mods exist in the Global/Eclipse.gitignore. Include that in your base gitignore and you'll be just fine

**Comment by chamfay** [comment]
OK Thanks.

**Pull request closed without merging**
