### PR TITLE
Update JetBrains.gitignore

### PR DESCRIPTION
**Pull request by mmanciop**
Adding *.iml to the ignore list for JetBrains/IntelliJ

**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by mmanciop** [comment]
Uhm, well, the *.iml is pretty much the default file format of IntelliJ community edition. Does https://intellij-support.jetbrains.com/hc/en-us/community/posts/206878055-Why-is-the-iml-file-stored-in-project-root- provide enough info?

**Comment by shiftkey** [comment]
@mmanciop not really, because `.iml` gets a shout out in [this doc](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839) which we cite at the top of the template:

**Comment by mmanciop** [comment]
I guess I am having some philosophical misunderstanding here. I always interpreted these .gitignore templates as “stuff not to version if you use tech X”.

In all teams I worked, we always excluded IDE setup files from versioning, except those like auto-formatting rules that become have to be imported. *.iml in particular are auto-generated by IntelliJ and seem to me to be equivalent more or less to .project in Eclipse, that is also something I would never version.

What am I missing here?

**Comment by develar** [comment]
I am responsible for configuration store. `*.iml` files should be committed. Since IntelliJ Platform 2017.2 even gradle/maven projects doesn't produce a lot of changed `*.iml` files (auto-generated data stored under system caches now).

> In all teams I worked, we always excluded IDE setup files from versioning

If you follow this rule, then this `.gitignore` is not for you — you can simply ignore the whole `/.idea/` and `*.iml` files. As far I see this file for those, who commit IntelliJ Platform project files into version control but still want to ignore known workspace-only files (`workspace.xml` and other such files).

**Comment by mmanciop** [comment]
Thanks for the explanations.

**Pull request closed without merging**
