### PR TITLE
Update Dart.gitignore

### PR DESCRIPTION
**Pull request by ArgentiApparatus**
1. Modify patterns to explicitly match directories

2. Modified patterns to match files and directories created by tools in Dart SDK 1.12:

    1. `pub` patterns:

        * Added patterns matching files listed in https://www.dartlang.org/tools/private-files.html

    2. `dart2js` patterns:

        * Added `*.js`, `*.precompiled.js` removed `*.js_`, `*.dart.js` to match files created by dart2js - see https://stackoverflow.com/questions/20314796/which-files-are-generated-when-executing-dart2js-and-why
        * Added `*.info.json` - see https://www.dartlang.org/tools/dart2js/

### CODE REVIEW

**Comment by shiftkey** [comment]
@ArgentiApparatus thanks for the first link, really explain it well.

Do you have a link summarizing the recommended changes for dealing with dart2js's output? I can only see these rules mentioned from the first link.

```
*.dart.js
*.js_
*.js.deps
*.js.map
```

**Comment by ArgentiApparatus** [comment]
https://www.dartlang.org/tools/private-files.html should be authoritative, but experiments with SDK 1.12 `dart2js` showed that `.js`, .`js.deps` and .`js.map` only are created. Presumably an earlier version of `dart2js` created that `.js_`.

I believe the contents of the Dart tools webpages are on Github, if so I'll look for or create a issue for that page. 

`pub` build creates a `.dart.js` file, but it is in the `./build/ directory`, and hence excluded by the `pub` patterns.

Note I pushed a commit to my branch adding `*.info.json` which I noticed when reading through https://www.dartlang.org/tools/dart2js/

**Comment by ArgentiApparatus** [comment]
A little more research turned up https://stackoverflow.com/questions/20314796/which-files-are-generated-when-executing-dart2js-and-why

I pushed another commit adding `*.precompiled.js`

**Comment by shiftkey** [comment]
@ArgentiApparatus thanks for the extra details. I'm happy to take this in.

**Comment by ArgentiApparatus** [comment]
Thanks!

**Pull request merged**
