### PR TITLE
Update Python.gitignore for celery-beat schedule binary file.

### PR DESCRIPTION
**Pull request by toanant**

### CODE REVIEW

**Comment by shiftkey** [comment]
Can you tell me a bit about what this change represents, and why it's a useful addition here?

**Comment by toanant** [comment]
Added this since in python based projects celery is common choice for asynchronous task queue and using celery-beat generate schedule's binary file which will vary from machine to machine, so it could be in gitignore.

**Comment by shiftkey** [comment]
@toanant thanks for the information! Unfortunately there's also a merge conflict which is preventing me from closing this out - is this something you can resolve?

**Comment by toanant** [comment]
@shiftkey I had resolved merge conflict.

**Comment by shiftkey** [comment]
@toanant thanks!

**Pull request merged**
