### PR TITLE
sync up xcode related gitignore files

### PR DESCRIPTION
**Pull request by bbodenmiller**
Xcode, Obj-C, & Swift updates. Also comment to help prevent fragmentation.

Some details based on #1221

### CODE REVIEW

**Comment by shiftkey** [comment]
Is it worth having a discussion about unifying these ignore files? We did this a while ago for `VisualStudio` - which was a combination of `CSharp` and `VisualBasic` languages - and I can't help but feel this is heading down that path...

**Comment by arcresu** [comment]
@shiftkey See comments on 5bd4330 for why we have the current state of these particular templates. I think it needs fixing, but people have strong feelings here.

**Comment by bbodenmiller** [comment]
Can we get these changes merged? Given the comments on the other thread I don't see a merge of the templates being feasible in the near future.

**Comment by shiftkey** [comment]
@bbodenmiller I'll give @arcresu a chance to chime in if has any issues with it, but I'm :thumbsup: with this change.

**Comment by arcresu** [comment]
Thanks, yeah this looks like a good change.

**Pull request merged**
