### PR TITLE
Add several downloaded files that should not be incorporated and remove .SRCINFO

### PR DESCRIPTION
**Pull request by marcelkorpel**
As of version 4.0.0 the Arch User Repository is build out of one git repository per package. The .SRCINFO files need to be included in those.

Moreover, I added several extensions of files that are regularly downloaded by PKGBUILD scripts; these shouldn't be included in git repositories of package sources.

### CODE REVIEW

**Comment by Zopieux** [comment]
I second that. I was about to open a similar PR!

**Comment by shiftkey** [comment]
@marcelkorpel @Zopieux any links to help us (and others) understand the changes better?

**Comment by marcelkorpel** [comment]
https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_4

**Comment by Zopieux** [comment]
> When making changes to the repository, make sure you always include the PKGBUILD and .SRCINFO in the top-level directory.

...
> the .SRCINFO must exist for every commit

**Comment by shiftkey** [comment]
Thanks for those details - I also found [this link](https://patchwork.archlinux.org/patch/2513/) which indicates `.AURINFO` contains the same contents as `SRCINFO`, but it named differently to indicate it's relevant to the AUR.

**Comment by marcelkorpel** [comment]
.SRCINFO is just the new name of .AURINFO; currently, the former is used by the AUR to parse metadata (to prevent parsing/executing possibly malicious bash scripts on the server).

**Pull request merged**
