### PR TITLE
Removed LaunchSettings.json from being committed

### PR DESCRIPTION
**Pull request by jasongaylord**
**Reasons for making this change:**
Removed Properites/launchSettings.json as others may be using other web servers and ports. Doesn't make sense to include my version.

**Links to documentation supporting these rule changes:** 
https://github.com/aspnet/Mvc/pull/3525

### CODE REVIEW

**Comment by shiftkey** [comment]
@jasongaylord the last comment seems interesting:

>  I'll back out the change once we get upgraded to new tooling.

And that was from November 2015. Does this mean it's not a bug with the tooling, and Working As Intended™?

**Comment by jasongaylord** [comment]
When you say....
> Does this mean it's not a bug with the tooling, and Working As Intended™

Are you asking if the launchSettings.json file should or should not be there? Even in the latest builds, it's there. It also appears in the team's version of .gitignore here: [https://github.com/aspnet/Mvc/blob/dev/.gitignore](https://github.com/aspnet/Mvc/blob/dev/.gitignore)

**Comment by shiftkey** [comment]
> Are you asking if the launchSettings.json file should or should not be there? 

Yeah, based on my reading of the initial issue it sounds like it's not a permanent thing.

@NTaylorMullen can you confirm this is intentional behaviour?  The discussion in https://github.com/aspnet/Mvc/pull/3525 suggests the .gitignore change is a workaround - just wanting to confirm that's no longer accurate.

**Comment by NTaylorMullen** [comment]
If you have customized debugger settings then having the `launchSettings.json` present is necessary. However, some might argue that customized debugger settings should be on a per-user basis (me being one of them) so `.gitignore`ing it is good.

To clarify the linked MVC PR. That was a bug where VS would automatically add a `launchSettings.json` on project open.

**Comment by shiftkey** [comment]
> should be on a per-user basis
> VS would automatically add a `launchSettings.json` on project open

@NTaylorMullen excellent, thanks for the context!

**Pull request merged**
