### PR TITLE
Update Vim.gitignore

### PR DESCRIPTION
**Pull request by guenti**
Added auto-generated tag files.

### CODE REVIEW

**Comment by shiftkey** [comment]
Do you have a link to what is responsible for this `tags` file, so that others can understand the context?

**Comment by guenti** [comment]
Of course. Some plugins creating tag files in a project folder automatically and a lot of developers creating the tag files per hand.

Here some examples of the plugins:
https://github.com/ludovicchabant/vim-gutentags
http://www.vim.org/scripts/script.php?script_id=3114

**Comment by shiftkey** [comment]
@guenti thanks!

**Comment by guenti** [comment]
Don't mention it! :)

**Pull request merged**
