### PR TITLE
Add trailing slash to .sass-cache

### PR DESCRIPTION
**Pull request by LayZeeDK**
Add trailing slash to `.sass-cache` to signify intent of matching directories.

### CODE REVIEW

**Comment by shiftkey** [comment]
As someone who's not familiar with SASS (i was in the LESS camp the last time I did web dev seriously) do you have a link to an explainer for this `sass-cache` folder?

**Comment by shiftkey** [comment]
The current `.sass-cache` rule will catch a directory named the same - is there something that's not working about this current setup?

**Comment by LayZeeDK** [comment]
I am under the impression that it is good practice to mark directories with a trailing slash in `.gitignore`s. Am I wrong?

**Comment by arcresu** [comment]
There are slight subtleties about the trailing slash when it comes to selectively un-ingnoring contents of the directory. In this case I don't think you'd ever want to do that, so it shouldn't make a difference, and the slash documents that it is a directory, so its presence is slightly preferable as far as I see.

I would recommend against mass-changing rules to add or remove slashes, though, because it's not always straightforward. I tend to leave the trailing slash or lack thereof as it was first introduced unless there is a specific problem to address.

**Comment by chenyunyou** [comment]
2506571489@qq.com

**Comment by arcresu** [comment]
I'll merge this because it seems fine, but with the note that in general changing trailing slashes without a specific motivation is probably not very useful and at worst could cause subtle issues.

**Pull request merged**
