### PR TITLE
Fixed LF and CRFL issue

### PR DESCRIPTION
**Pull request by Pranavmn**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by Pranavmn** [comment]
Fixes the issue.

**Comment by drothmaler** [comment]
Looks like `.gitconfig` entries, but definitely not something that should go into a gitignore files...

**Comment by shiftkey** [comment]
> Fixes the issue.

@Pranavmn without more context about what this is potentially fixing, I cannot accept this change. As @drothmaler points out, this looks like the contents of a `.gitconfig` file.

**Comment by Pranavmn** [comment]
Oh sorry there was a mistake I meant to make that change to my own
gitignore file in my repository and not make a suggestion to you guys.
Sorry about that.

**Pull request closed without merging**
