### PR TITLE
ReactJS

### PR DESCRIPTION
**Pull request by mr2rm**
**Reasons for making this change:**

Recently I need common gitignores to create and publish my own ReactJS projects. So I tried to find and collect some of them which can be usable for everyone and it can be updated during the time.

**Links to documentation supporting these rule changes:**

https://www.npmjs.com/
https://yarnpkg.com/
http://nodejs.org/api/addons.html
https://nodejs.org/api/modules.html
https://jspm.org/docs/guide
https://bower.io/docs/api/
https://eslint.org/
https://www.typescriptlang.org/
http://gruntjs.com/creating-plugins#storing-task-files
https://www.npmjs.com/package/jscoverage
https://tntim96.github.io/JSCover/
https://istanbul.js.org/
https://www.npmjs.com/package/node-waf

If this is a new template:

 - **Link to application or project’s homepage**: At the moment, there is no public or published application which I can mention it; but in the future it can be turned into a new template.

### CODE REVIEW

**Comment by deemoding** [comment]
Maybe you can use node.ignore rather than add a new ignore file.

**Comment by nickmccurdy** [comment]
I don't see any major advantages to this over using the existing Node gitignore or the one provided by create-react-app. Besides, the exact files you're using really depend on your build tooling.

**Comment by bdougie** [comment]
This seems like a lot of duplicated work. Also, the majority of React starters and templates work off of [Node.gitignore](https://github.com/github/gitignore/blob/main/Node.gitignore). I don't see any reason to merge this, unless I am missing something.

**Comment by bdougie** [comment]
Closing, since the Node.gitignore already ignores framework and library-specific files. Also a template for a Framework should be in the community folder per the guidelines.

**Pull request closed without merging**
