### PR TITLE
Update Android.gitignore to include Android Studio nav temp files

### PR DESCRIPTION
**Pull request by SamWhited**
Gitignore the temp files directory generated by Android Studio's navigation editor tool.

To generate this directory open a project in Android Studio, then navigate to `tools -> android -> navigation editor`. This directory contains screenshots of the various activities and menues in the project which are used to build a navigation tree.

### CODE REVIEW

**Comment by saygun** [comment]
+1

**Comment by thiagokimo** [comment]
+1

**Comment by shiftkey** [comment]
Do you have a link to the documentation for the navigation editor (so we can point curious users to it)?

**Comment by SamWhited** [comment]
@shiftkey http://tools.android.com/navigation-editor

**Comment by shiftkey** [comment]
@SamWhited thanks!

**Pull request merged**
