### PR TITLE
Created AptanaStudio.gitignore

### PR DESCRIPTION
**Pull request by gautamkrishnar**
**Reasons for making this change:**

Aptana studio Git-ignore was not available

**Links to documentation supporting these rule changes:** 
http://www.aptana.com/support.html

If this is a new template: **YES**

http://www.aptana.com

Also attaching a sample project directory screenshot:
screenshot 30

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
cc: @defunkt @pjhyett @technoweenie @Caged  @jnewland

**Comment by drothmaler** [comment]
Thank you for your work on this gitignore-file...
Just two little hints: 
1.: as  Aptana Studio is a Tool/IDE, it's gitignore file should be placed inside the "Global" directory.
2.: Aptana Studio seems to be based on Eclipse. So it might be better to just create a symlink to the `Global/Eclipse.gitignore` instead of creating a new one.

**Comment by gautamkrishnar** [comment]
moved... How to create the symlink? @drothmaler

**Comment by drothmaler** [comment]
In OSX/Linux you can easily create one, using `ln -s Eclipse.gitignore AptanaStudio.gitignore` and doing a regular `git add` / `git commit` afterwards. But it seams that you are using Windows, and I have never created one there. 
It seems that you can use `mklink` these days. Try: `mklink AptanaStudio.gitignore Eclipse.gitignore` (but without any guarantee :-))
You could also try the [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html), if you prefer a GUI.

**Comment by gautamkrishnar** [comment]
@drothmaler symlinked it using linux...

**Comment by gautamkrishnar** [comment]
@drothmaler Shall i have to close this one?

**Comment by drothmaler** [comment]
@gautamkrishnar I don't know; I'm not a member of the gitignore team :-)

**Comment by shiftkey** [comment]
@drothmaler @gautamkrishnar I'll have a look through this after I return from a holiday next week.

**Pull request closed without merging**
