### PR TITLE
MicrosoftOffice.gitignore case-insensitivity

### PR DESCRIPTION
**Pull request by Sduibek**
Added case-insensitivity for temp files.

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks, but could you explain why this is necessary? If you're using a case-insensitive filesystem then this is unnecessary, and if you're not on Windows then it's too late for gitignore rules to help you.

**Comment by Sduibek** [comment]
Hello! I apologize for the delay in responding to this.

Does git/GitHub ignore case to begin with?

Some of the current .gitignore templates do have declarations that specify case-insensitivity with the [], so I assumed case-insensitivity in such declarations was useful.

**Comment by arcresu** [comment]
As I understand it, git is case sensitive if the underlying filesystem is case sensitive. If you haven't run into any specific problem with this rule, then it's probably not worth making rules case agnostic just in case.

**Comment by Sduibek** [comment]
Okay, fair enough. I will go ahead and close this.

Thank you.

**Pull request closed without merging**
