### PR TITLE
Ignoring spyder project settings

### PR DESCRIPTION
**Pull request by hippo91**
No need to push .spyderpoject file in a python project.
https://github.com/spyder-ide/spyder

### CODE REVIEW

**Comment by shiftkey** [comment]
Apologies for the delay in reviewing this. Aside from the merge conflict, I have no issues with this PR.

**Comment by shiftkey** [comment]
I'm trying to clear out the backlog of PRs here, and given the comments haven't seen a reply I'm going to close this out.

@hippo91 please let me know if you're interested in working together so this can get merged in.

**Comment by hippo91** [comment]
Hi,

Sorry for the delay.
I'm not yet very familiar with PR system so i thought that i didn't have to
answer your preceding email.
Will my PR be merged or should i do something else?

Thank you

hippo91

2016-03-06 9:34 GMT+01:00 Brendan Forster <notifications@github.com>:

**Comment by shiftkey** [comment]
@hippo91 the file conflict means I can't automatically merge the PR. I think it's going to be easier (and quicker) for you to open a new PR with the same change, rather than deal with the conflict. Does that make sense?

**Comment by hippo91** [comment]
OK, I'm doing this now!

2016-03-06 11:50 GMT+01:00 Brendan Forster <notifications@github.com>:

**Comment by hippo91** [comment]
It's done! Apparently no merge conflict ths time!


2016-03-06 12:06 GMT+01:00 guillaume Peillex <guillaume.peillex@gmail.com>:

**Pull request closed without merging**
