### PR TITLE
Create IAR.gitignore

### PR DESCRIPTION
**Pull request by diffstorm**
**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:** 

_TODO_

If this is a new template: 

 - **Link to application or project’s homepage**: _TODO_

gitignore for IAR Embedded Workbench

### CODE REVIEW

**Comment by joeblau** [comment]
@diffstorm - This tempalte is live on [gitignore.io](https://www.gitignore.io) - https://www.gitignore.io/api/iar

**Comment by diffstorm** [comment]
Can we merge this? IAR is quite a popular compiler with IDE https://www.iar.com

**Review by wirecat — APPROVED** [review]
Thank you for contributing!

**Comment by wirecat** [comment]
@diffstorm could you try forward integrating our main branch into your development branch?
I'm getting an error when attempting the merge and I _think_ that should resolve it.

**Comment by diffstorm** [comment]
@wirecat Thanks. I think the branch from 2016 was deleted, just created another branch to fix this.

https://github.com/github/gitignore/pull/4454

**Pull request closed without merging**
