### PR TITLE
Add .gitignore for FreePascal (http://www.freepascal.org) and Lazarus…

### PR DESCRIPTION
**Pull request by davegorst**
**Reasons for making this change:**

Currently missing.

**Links to documentation supporting these rule changes:** 

http://wiki.freepascal.org/file_types

**Link to application or project’s homepage**: 

http://www.freepascal.org
http://www.lazarus-ide.org

### CODE REVIEW

**Comment by joeblau** [comment]
@davegorst - Does this template solve what you're looking for? https://github.com/dvcs/gitignore/blob/37adf08cf5e2cbd75077c2d4eef00082b5a5a554/templates/Lazarus.gitignore

You can access it at: https://www.gitignore.io

**Comment by davegorst** [comment]
It certainly looks like it. I hadn't seen this fork - it might be an 
idea to feed all this back into the source wiki.

Thanks,
Dave.

------ Original Message ------

**Comment by joeblau** [comment]
You can definitely add it to the source wiki.

**Comment by shiftkey** [comment]
I'm going to close this out because there is a `Global/Lazarus.gitignore` that already defines all these rules.

**Pull request closed without merging**
