### PR TITLE
Update Joomla.gitignore

### PR DESCRIPTION
**Pull request by ivanramosnet**
Update to Joomla 3.4.1 files.

### CODE REVIEW

**Comment by shiftkey** [comment]
@ivanramosnet apologies for not getting back to this sooner - I was kind of overwhelmed and not sure where to start. Is there some documentation from the Joomla team about what can be ignored from version control, or is this just something from your experience?

Also, there's a merge conflict in here - are you interested in resolving that so I can help merge this in?

**Comment by ivanramosnet** [comment]
This change is something from my experience and I can resolve the conflict without problem.

**Comment by shiftkey** [comment]
@ivanramosnet any updates?

**Comment by shiftkey** [comment]
Closing due to inactivity and conflicts. @ivanramosnet please have a look at the latest Joomla file and see if anything else needs to be changed.

**Pull request closed without merging**
