### PR TITLE
update license to CC0

### PR DESCRIPTION
**Pull request by shiftkey**
This replaces the original MIT license with [CC0](https://creativecommons.org/about/cc0) as it feels like a more suitable license for the `gitignore` templates we maintain here, and has more clarity than the changes proposed in #752.

cc @haacked who proposed the initial PR
cc @bkeepers @benbalter @cobyism @aroben @bhuga who were involved in that PR

### CODE REVIEW

**Comment by shiftkey** [comment]
Gonna let this sit for a few days to give everyone a chance to contribute.

**Comment by revi** [comment]
To relicense, all contributors have to agree relicense, since they still retain the copyright.

**Comment by shiftkey** [comment]
@revi as the previous public domain pull request github/gitignore#752 noted .gitignore files are too trivial to be subject to copyright. We're just making it clear now that no you don't have to copy around the MIT license and our copyright notice when using any of these .gitignore files in your projects, not that anyone ever did anyway. If we had any code in this repo you're right, getting agreement from all contributors would be necessary, if very painful.

**Comment by nathanmusoke** [comment]
> Gonna let this sit for a few days to give everyone a chance to contribute.

Any updates? It's been six months, so I'm guessing no one will object until this is actually merged.

**Comment by shiftkey** [comment]
@nathanmusoke excellent point - and thanks for the reminder. I'll poke the relevant people on my side but I don't anticipate further issues.

**Pull request merged**
