### PR TITLE
Adds Move language

### PR DESCRIPTION
**Pull request by gregnazario**
**Reasons for making this change:**
I am a core contributor to the Aptos blockchain https://github.com/aptos-labs/aptos-core, and I've written enough Move contracts to be inconvenienced / copy the same .gitignore between each.  Trying to make it as simple as possible for onboarding.

Move language is used for MoveVM based blockchains as the language native to them.  The compiler provides a folder build/ that holds the build artifacts.

The .aptos/ folder is ignored so people do not upload their private keys to a git repository.

**Links to documentation supporting these rule changes:**
Here's the [Move book](https://aptos.dev/move/book/SUMMARY), though, it looks like it doesn't explicitly say that this comes from the compiler.

Example:
```
$ ls
Move.toml sources
$ aptos move compile --dev
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Coin
{
  "Result": [
    "0000000000000000000000000000000000000000000000000000000000111111::coin"
  ]
}
$ ls
Move.toml build     sources
```

This applies to all blockchains that use the Move compiler.

Additionally, for Aptos specifically the Aptos CLI adds an account it'll create a file structure like below where the config.yaml has credentials in it:
```
$ ls -a
.          ..         .aptos     .gitignore Move.toml  build      sources
$ ls .aptos
config.yaml
```

It's best that all Move blockchains add anything here that may add unwanted credentials associated with their blockchains.

If this is a new template:

 - **Link to application or project’s homepage**: [Aptos Foundation](https://aptosfoundation.org/)

### CODE REVIEW

**Comment by gregnazario** [comment]
@martinwoodward, what do we have to do to get these merged?

**Comment by gregnazario** [comment]
@wirecat any chance you could look at this one?

**Comment by gregnazario** [comment]
@dooleydevin mind taking a look at this?

The main important thing here is that, by providing this, users are less likely to share their credentials accidentally in repositories.

**Comment by dooleydevin** [comment]
@gregnazario the gitignore file makes sense to me 😄 since move is a pretty specialized language, would you mind moving this under the `community` directory?

**Comment by dooleydevin** [comment]
> > @gregnazario the gitignore file makes sense to me 😄 since move is a pretty specialized language, would you mind moving this under the `community` directory?
> 
> Sure, that works for me. Will it show up under the general github .gitignore search?

It will not, but it will be available for copying as you need and it allows other Move developers to collaborate on the file 👍

**Comment by gregnazario** [comment]
> > > @gregnazario the gitignore file makes sense to me 😄 since move is a pretty specialized language, would you mind moving this under the `community` directory?
> > 
> > 
> > Sure, that works for me. Will it show up under the general github .gitignore search?
> 
> It will not, but it will be available for copying as you need and it allows other Move developers to collaborate on the file 👍

Hmm... I guess that's okay for now, but I think the focus on getting it into the main .gitignore list was to prevent people from uploading their credentials accidentally.

**Comment by gregnazario** [comment]
@dooleydevin mind giving it a look again :). Thanks!

**Pull request merged**
