### PR TITLE
Update VisualStudio.gitignore

### PR DESCRIPTION
**Pull request by reddyjannavarapu**
added for sloution files

### CODE REVIEW

**Comment by alexgwolff** [comment]
But without these files visual studio can't open solution. 
these files are necessary

**Comment by shiftkey** [comment]
@reddyjannavarapu `.csproj` and `.sln` files are essential for many different types of VS projects - can you tell me a bit about why you think they should be ignored?

**Comment by drothmaler** [comment]
-1

**Comment by dariusdamalakas** [comment]
Please can someone close this PR, both file types need to be in source control

**Comment by shiftkey** [comment]
@dariusdamalakas I'm not convinced these should be included by default - Visual Studio needs these to manage the solutions and projects a user can create.

**Comment by dariusdamalakas** [comment]
@shiftkey, well that's exactly what i've said :+1:  Thanks for closing this.

**Pull request closed without merging**
