### PR TITLE
Update Java.gitignore

### PR DESCRIPTION
**Pull request by DUFCLiam**
**Reasons for making this change:**
I would like .java added to it, As that file can be used.

**Links to documentation supporting these rule changes:** 
None provided sorry.

### CODE REVIEW

**Comment by shiftkey** [comment]
@DUFCLiam this will exclude Java source files from version control, which feels very dangerous. Could you clarify why this is necessary?

**Comment by DUFCLiam** [comment]
I am sorry, My brother had access to my laptop therefore he had access to GitHub sorry for any inconvenience caused.

**Comment by shiftkey** [comment]
@DUFCLiam all good, thanks for confirming!

**Comment by DUFCLiam** [comment]
You're welcome :) @shiftkey

**Pull request closed without merging**
