### PR TITLE
Add drupal 8 and above ignore file

### PR DESCRIPTION
**Pull request by mourad-zitouni**
**Reasons for making this change:**
The existing file is compatible with drupal 7, this file is for later versions (8/9/10...)

### CODE REVIEW

**Comment by bdougie** [comment]
Thanks for the contribution, but we will need more context about this change. Please explain the reason for divergence in Drupal and why the existing file does not support Drupal 8.

**Comment by mourad-zitouni** [comment]
In fact there have been changes in the folder structure of Drupal in version 8, also they introduced composer to manage dependencies and because of that Drupal core and contributed modules files (and all their dependencies) are no longer part of the repository (they are downloaded by composer).

**Comment by bdougie** [comment]
I believe that is all covered in this PR https://github.com/github/gitignore/pull/3386 which I will go ahead merge now.

**Comment by lpalgarvio** [comment]
> I believe that is all covered in this PR #3386 which I will go ahead merge now.

correct, plus there are wrong paths here in this PR.
contributed modules, themes, etc go in /sites/all/* or /sites/[sitename]/*

**Comment by lpalgarvio** [comment]
> > I believe that is all covered in this PR #3386 which I will go ahead merge now.
> 
> correct, plus there are wrong paths here in this PR. contributed modules, themes, etc go in [root]/sites/all/* or [root]/sites/[sitename]/* for drupal7 and [root]/* or [root]/sites/all/* or [root]/sites/[sitename]/* for drupal 8

after all might need future review for paths, im seeing new references in some places

**Pull request closed without merging**
