### PR TITLE
Add folder attributes

### PR DESCRIPTION
**Pull request by vgturtle127**
Added some folder attributes from a previous PR.

@shiftkey

### CODE REVIEW

**Comment by vgturtle127** [comment]
@shiftkey Actually, I can see some from PR #1499 that we could add. Should I?

**Comment by shiftkey** [comment]
Ugh, this still looks like it's changing the line endings :sob:

**Comment by vgturtle127** [comment]
@shiftkey Oh, crap! I don't have any global configs, and I used the GitHub editor!

Should I try locally?

**Comment by shiftkey** [comment]
@vgturtle127 I guess that's the only option then :(

**Comment by vgturtle127** [comment]
@shiftkey What are the line endings that won't mess it up, and should I close this and start over? :laughing:

**Comment by shiftkey** [comment]
I think I need to review this change outside of the PR view, something doesn't feel right...

**Comment by vgturtle127** [comment]
@shiftkey I know I suggested this earlier, and I think you said something about it, but why couldn't we add a .gitattributes to the repo? That would automatically normalize all the files to the native OS encodings...

**Comment by vgturtle127** [comment]
@shiftkey Actually, never mind. I just messed another project up by adding the .gitattributes file...

**Pull request closed without merging**
