### PR TITLE
Fix Prestashop unwanted gitignored directory

### PR DESCRIPTION
**Pull request by PrestanceDesign**
The line `cache/` causing problem for gitignore important class directory and files `classes/cache/*`.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
I didn't realized when I wrote it ! Thank you !

I think it would be better to add a slash at the beginning to specify we only want to ignore the cache folder in the root directory:
```
/cache
```

Like if you have a module about cache or something, there might be a important folder named cache and you don't want to ignore it.

**Comment by PrestanceDesign** [comment]
> I think it would be better to add a slash at the beginning to specify we only want to ignore the cache folder in the root directory

Yes I agree, it's better. I'll update my PR immediatly.

**Comment by PrestanceDesign** [comment]
OK, you've already done. I close this PR.

**Comment by julienbourdeau** [comment]
Hey, I've done it on the PrestaShop/PrestaShop repo, you still need to do it here to update the gitignore provided by github :)
You should update and reopen it.

**Comment by PrestanceDesign** [comment]
I already does in this new PR #1694.
Thx @julienbourdeau for the advice.

**Comment by julienbourdeau** [comment]
Great ! :+1:

**Pull request closed without merging**
