### PR TITLE
[Objective-C / Swift] Updated fastlane docs

### PR DESCRIPTION
**Pull request by KrauseFx**
Updated `fastlane` docs to link to a more complete documentation if the user wants more recommendation / options.

### CODE REVIEW

**Comment by shiftkey** [comment]
Should this also be added to `Global/Xcode.gitignore` ?

**Comment by KrauseFx** [comment]
Should it? I'm okay with either solutions. `fastlane` works with any Xcode project.

**Comment by shiftkey** [comment]
@KrauseFx apologies, I thought there was a section for `fastlane` there. And there's not.

:shipit:

**Comment by KrauseFx** [comment]
Cool, thanks for merging @shiftkey :rocket:

**Pull request merged**
