### PR TITLE
OSX.gitignore additions

### PR DESCRIPTION
**Pull request by Sduibek**
Added __MACOSX folder and missing descriptions.

### CODE REVIEW

**Comment by arcresu** [comment]
Thanks, but could you explain what this rule is intended to fix? Is there any documentation?

**Comment by Sduibek** [comment]
Hello! I apologize for the delay in responding to this.

Well first of all I added a brief explanation/summary to entries that previously did not have any. Presumably this change is self-explanatory, no pun intended.

I couldn't find any explanations for .LSOverride via Google searches, hence why I added "?" as the explanation for that one. (I realize this probably isn't standard procedure but I wasn't sure what else to do there.)

Regarding the new entry, "__MACOSX/", it's a very common path on Mac systems with plentiful results if you do a web search for it. It only shows up on non-Mac systems, and is useless for non-Mac systems, hence the ignore entry.

It is involved with their handling of compressed archives:
http://superuser.com/questions/104500/what-is-macosx-folder
http://old.floatingsun.net/2007/02/07/whats-with-__macosx-in-zip-files/
http://www.quora.com/Why-do-Macs-create-a-__MACOSX-folder-in-a-zip-file
http://wpguru.co.uk/2013/10/how-to-remove-__macosx-from-zip-archives/
http://stackoverflow.com/questions/10924236/mac-zip-compress-without-macosx-folder

**Comment by vgturtle127** [comment]
@arcresu Can we merge this?

**Comment by shiftkey** [comment]
I can't take this in as-is, as the line endings have changed and will regress this rule:

```
# Icon must end with two \r
Icon

```

cc @Sduibek

**Comment by vgturtle127** [comment]
This might sound stupid, but could you add a .gitignore to the .gitignore repo to normalize line endings? :laughing: 

I mean, talk about meta, but it could work right?

**Comment by shiftkey** [comment]
@vgturtle127 I don't think that will address the problem here, as it's been rather easy to break in the past https://github.com/github/gitignore/pull/804

**Comment by vgturtle127** [comment]
Oh, the problem is simply with the Icon that needs two /r line endings in order to work?

We can probably remove that, or I can force the line endings in Notepad++.

Are line endings not normalized in this repository? If figured they would all be normalized into Unix format (or /LF as it is sometimes called)?

**Comment by shiftkey** [comment]
> Are line endings not normalized in this repository?

No, there is no `.gitattributes` file defined in this repository

**Comment by shiftkey** [comment]
> We can probably remove that, or I can force the line endings in Notepad++.

Me being rather lazy, I'd just edit the file on the site and create a new PR...

**Comment by vgturtle127** [comment]
@shiftkey I can do that if you want.

**Comment by shiftkey** [comment]
@vgturtle127 let's close this out and start afresh

**Comment by vgturtle127** [comment]
@shiftkey So what do you want me to do? :smile:

**Comment by shiftkey** [comment]
@vgturtle127 that'd be great, I've got a lot of other things to review :grin:

**Comment by vgturtle127** [comment]
@shiftkey What would be great? :laughing: 

Do you want me to do a PR for all the Mac OS X stuff?

**Comment by shiftkey** [comment]
@vgturtle127 sorry I wasn't clear enough. This is the interesting change from the original PR:

```diff
# Folder attributes
  .DS_Store
 +
 +# Resource Forks
 +__MACOSX/
```

**Comment by vgturtle127** [comment]
@shiftkey OK, just wanted to make sure I knew what I was doing. :laughing:

**Pull request closed without merging**
