### PR TITLE
Added .htaccess to concrete5 gitignore

### PR DESCRIPTION
**Pull request by littleibex**
Updated concrete5 gitignore to include htaccess

### CODE REVIEW

**Comment by shiftkey** [comment]
@littleibex can you tell me about why this file should be excluded? Is there a specific tool that's creating this?

**Comment by littleibex** [comment]
It's created  when you enable pretty URLs in concrete5. The htaccess file on the server can have a lot of settings in htaccess which I believe you should not be overwritten by the local repository.

**Comment by shiftkey** [comment]
> The htaccess file on the server can have a lot of settings in htaccess which I believe you should not be overwritten by the local repository.

To make sure I understand: typically the `.htaccess` file on the server is not in version control, and you will want whatever's there rather than whatever's created locally?

**Comment by littleibex** [comment]
.htaccess file is not there initially in the project. However, after a particular setting from the CMS is enabled, the .htaccess file is created in the root of the project which then becomes a part of the repository. It's not good to have .htaccess in version control since, more than the project, it's associated to the server or machine where it is hosted.

**Comment by shiftkey** [comment]
@littleibex apologies for the delay - this all seems reasonable. Thanks!

**Pull request merged**
