### PR TITLE
Update Go.gitignore -> Added .env

### PR DESCRIPTION
**Pull request by LombardiDaniel**
**Reasons for making this change:**

I use the default Go gitignore and it should have .env in it by default

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Review by philfreshman — APPROVED** [review]
LGTM

**Review by wirecat — CHANGES_REQUESTED** [review]
Could you please provide a bit more context around why you believe this should be added?

Also, we currently have some merge conflicts that will need resolved.

**Comment by LombardiDaniel** [comment]
@wirecat resolved! The main reason for this change is just that so many apps do need some sort of .env file to keep secrets while on development, me and a couple of colleagues have accidently uploaded our .env files with API keys to git in go projects because we did not check the .gitignore (just assumed that `.env` was in there, as is the case with lots of other default .gitignores files)

**Review by wirecat — APPROVED** [review]
@LombardiDaniel Thank you for resolving the merge conflict and adding clarification!

**Pull request merged**
