### PR TITLE
[Java] added *.properties

### PR DESCRIPTION
**Pull request by xxammuxx**
*.properties

**Reasons for making this change:**

_TODO_

**Links to documentation supporting these rule changes:**

_TODO_

If this is a new template:

 - **Link to application or project’s homepage**: _TODO_

### CODE REVIEW

**Comment by shiftkey** [comment]
@xxammuxx any links to StackOverflow discussions or other documentation about this change?

**Comment by Tristan971** [comment]
The Spring project, Java's most popular web application framework (see https://dzone.com/articles/most-popular-java-web-frameworks for example), relies on those heavily ; they should definitely not be ignored. See : https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by shiftkey** [comment]
@Tristan971 thanks for the link. And these paths can be _safely_ ignored from version control? Users won't expect these files to be committed and tracked?

**Comment by shiftkey** [comment]
@xxammuxx given the link from @Tristan971 above, does it still make sense to add this rule?

**Comment by Tristan971** [comment]
No they indeed cannot be ignored and should 100% be version controlled.
Unfortunately I do not believe this PR is good in the long term.

**Comment by xxammuxx** [comment]
@Tristan971 is right about it. This can be ignored.

**Pull request closed without merging**
