### PR TITLE
Update Rust.gitignore

### PR DESCRIPTION
**Pull request by deepak**
no need to specifically ignore compiled files and executables
as it will be under the target directory

this is as per this [comment](https://github.com/rust-lang/cargo/issues/2565#issuecomment-209474212)
in the rust repo

### CODE REVIEW

**Comment by shiftkey** [comment]
Is this a recent change in Rust or do we assume most users will be on the right version?

**Comment by elifoster** [comment]
This has been the case for as long as I have known about Rust, which is at least 2 years ago. Additionally, most Rust projects I've seen and worked on have had gitignores pretty much only consisting of the target directory.

**Comment by shiftkey** [comment]
@elifoster cool - if there's a good example elsewhere we can cite I'm happy to run with this change!

**Comment by elifoster** [comment]
There's the issue in the Rust repo that @deepak linked. There is also all the Rust repositories which ignore solely target:
* [rust-lang/cargo](https://github.com/rust-lang/cargo/blob/master/.gitignore#L1)
* [rust-lang/libc](https://github.com/rust-lang/libc/blob/master/.gitignore#L1)
* [rust-lang/rust](https://github.com/rust-lang/rust/blob/master/.gitignore#L98)
* [rust-lang/crates.io](https://github.com/rust-lang/crates.io/blob/master/.gitignore#L1)
* [rust-lang/rust-by-example](https://github.com/rust-lang/rust-by-example/blob/master/.gitignore#L7)

**Comment by shiftkey** [comment]
@elifoster excellent, thanks!

**Comment by deepak** [comment]
thanks @elifoster and @shiftkey

**Pull request merged**
