### PR TITLE
Windows Azure Emulator

### PR DESCRIPTION
**Pull request by m1stegmann**
Ignoring directory "efc" and "rfc" created by the Windows Azure Emulator

Directory before starting emulator the first time:

Directory: C:\temp\AzureCloudService1\AzureCloudService1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/1/2015   9:16 AM                bin
d-----         9/1/2015   9:16 AM                WorkerRole1Content
-a----         9/1/2015   9:16 AM           3014 AzureCloudService1.ccproj
-a----         9/1/2015   9:16 AM            144 AzureCloudService1.ccproj.user
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Cloud.cscfg
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Local.cscfg
-a----         9/1/2015   9:16 AM            428 ServiceDefinition.csdef

And after starting the Emulator:

Directory: C:\temp\AzureCloudService1\AzureCloudService1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/1/2015   9:16 AM                bin
d-----         9/1/2015   9:19 AM                csx
d-----         9/1/2015   9:19 AM                ecf
d-----         9/1/2015   9:19 AM                obj
d-----         9/1/2015   9:19 AM                rcf
d-----         9/1/2015   9:16 AM                WorkerRole1Content
-a----         9/1/2015   9:16 AM           3014 AzureCloudService1.ccproj
-a----         9/1/2015   9:16 AM            144 AzureCloudService1.ccproj.user
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Cloud.cscfg
-a----         9/1/2015   9:16 AM            505 ServiceConfiguration.Local.cscfg
-a----         9/1/2015   9:16 AM            428 ServiceDefinition.csdef

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks!

**Comment by khellang** [comment]
The .gitignore and commit message says `efc` and `rfc`, but the directory dump (also part of commit message) says `ecf` and `rcf`. Which is it?

**Comment by shiftkey** [comment]
Oops. @m1stegmann can you clarify?

**Comment by m1stegmann** [comment]
The dump with "ecf" and "rcf" ist correct

**Comment by khellang** [comment]
Which means that the .gitignore is *not* :smile.

**Pull request merged**
